-- =============================================================================
-- MIRRORED FROM PebbleFlow-ai/PebbleFlow @ 086183dee7deffb60c3c9355537d698237cabc60
-- Source path: cloud/relay/db/schema.sql
-- Mirrored at: 2026-04-25T02:01:26Z
--
-- This file is auto-generated by the mirror-transparency workflow.
-- Do not edit here. Changes must land in the private monorepo first.
-- =============================================================================

-- PebbleFlow D1 (SQLite) Schema
-- Translated from PostgreSQL. Application must:
--   - Generate UUIDs for all TEXT PRIMARY KEY columns
--   - Set updated_at on every UPDATE
--   - Compute any derived/generated columns

-- ============================================================
-- 1. users
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
  id                        TEXT PRIMARY KEY,
  email                     TEXT NOT NULL UNIQUE,
  password_hash             TEXT,
  email_verified            INTEGER NOT NULL DEFAULT 0,
  email_verify_token        TEXT,
  email_verify_expires_at   TEXT,
  password_reset_token      TEXT,
  password_reset_expires_at TEXT,
  name                      TEXT,
  avatar_url                TEXT,
  tier                      TEXT NOT NULL DEFAULT 'free'
                            CHECK (tier IN ('free', 'pro', 'platform', 'tester')),
  google_id                 TEXT UNIQUE,
  apple_id                  TEXT UNIQUE,
  stripe_customer_id        TEXT UNIQUE,
  onboarding_complete       INTEGER DEFAULT 0,
  failed_login_attempts     INTEGER NOT NULL DEFAULT 0,
  locked_until              TEXT,
  login_challenge_token     TEXT,
  login_challenge_expires_at TEXT,
  last_active_at            TEXT,
  created_at                TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at                TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================================
-- 2. licenses
-- ============================================================
CREATE TABLE IF NOT EXISTS licenses (
  id                      TEXT PRIMARY KEY,
  license_key             TEXT NOT NULL UNIQUE,
  tier                    TEXT NOT NULL DEFAULT 'free'
                          CHECK (tier IN ('free', 'pro', 'platform', 'tester')),
  status                  TEXT NOT NULL DEFAULT 'active'
                          CHECK (status IN ('active', 'trial', 'expired', 'revoked', 'suspended')),
  user_id                 TEXT REFERENCES users(id) ON DELETE SET NULL,
  bound_at                TEXT,
  valid_from              TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at              TEXT,
  activation_count        INTEGER NOT NULL DEFAULT 0,
  max_activations         INTEGER NOT NULL DEFAULT 5,
  last_validated_at       TEXT,
  notes                   TEXT,
  stripe_subscription_id  TEXT,
  stripe_customer_id      TEXT,
  trial_started_at        TEXT,
  trial_ends_at           TEXT,
  grace_period_ends_at    TEXT,
  grace_extended_by       TEXT REFERENCES users(id),
  grace_extended_at       TEXT,
  grace_extension_notes   TEXT,
  licensed_apps           TEXT,          -- JSON array of app buckets (e.g., '["ios"]'). NULL = all apps.
  source                  TEXT DEFAULT 'stripe', -- Payment rail: 'stripe', 'apple-iap', 'google-play', 'manual'
  trial_licensed_app      TEXT,          -- App bucket the trial is bound to. NULL = legacy global trial.
  licensed_apps_changed_at TEXT,         -- Last licensedApps change (30-day cooldown enforcement)
  app_account_token       TEXT,          -- Apple IAP: PebbleFlow user UUID passed as Product.PurchaseOption.appAccountToken to bind the transaction to the account that initiated the purchase. See migration 013.
  original_transaction_id TEXT,          -- Apple IAP: stable transaction identifier used for webhook renewals/refunds. Also stored with "apple:" prefix in stripe_subscription_id for backward compat.
  created_at              TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at              TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_licenses_original_transaction_id ON licenses(original_transaction_id);
CREATE INDEX IF NOT EXISTS idx_licenses_app_account_token ON licenses(app_account_token);

-- ============================================================
-- 3. subscriptions
-- ============================================================
CREATE TABLE IF NOT EXISTS subscriptions (
  id                      TEXT PRIMARY KEY,
  user_id                 TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  plan_id                 TEXT NOT NULL,
  plan_name               TEXT,
  status                  TEXT NOT NULL DEFAULT 'active'
                          CHECK (status IN ('active', 'trial', 'cancelled', 'non_renewing', 'paused', 'future', 'past_due')),
  stripe_subscription_id  TEXT UNIQUE,
  stripe_customer_id      TEXT,
  current_term_start      TEXT,
  current_term_end        TEXT,
  trial_end               TEXT,
  cancelled_at            TEXT,
  cancel_reason           TEXT,
  mrr_cents               INTEGER,
  currency                TEXT DEFAULT 'USD',
  created_at              TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at              TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================================
-- 4. user_provisioned_keys
-- ============================================================
-- PebbleFlow-owned OpenRouter credentials provisioned directly (not via
-- user OAuth) for per-user metered free-tier access. NOT user-owned
-- secrets — they are PF service keys held on PF's own OpenRouter account.
-- `api_key` is encrypted at rest with PF_TOKEN_SECRET via
-- relay/api/crypto.ts → encryptAtRest(). See relay/api/openrouter-oauth.ts
-- for the parallel read/write path used by pf_service_keys.
-- ============================================================
CREATE TABLE IF NOT EXISTS user_provisioned_keys (
  id                TEXT PRIMARY KEY,
  user_id           TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  key_hash          TEXT NOT NULL,
  api_key           TEXT NOT NULL,                    -- encrypted at rest with PF_TOKEN_SECRET; see relay/api/crypto.ts
  key_name          TEXT NOT NULL,
  credit_limit      REAL NOT NULL DEFAULT 0.0,
  credits_used      REAL NOT NULL DEFAULT 0.0,
  is_active         INTEGER NOT NULL DEFAULT 1,
  disabled_at       TEXT,
  disabled_reason   TEXT,
  created_at        TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at        TEXT NOT NULL DEFAULT (datetime('now')),
  last_synced_at    TEXT
);

-- ============================================================
-- 5. credit_purchases
-- ============================================================
CREATE TABLE IF NOT EXISTS credit_purchases (
  id                          TEXT PRIMARY KEY,
  user_id                     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount_usd                  REAL NOT NULL,
  credits_added               REAL NOT NULL,
  stripe_checkout_session_id  TEXT UNIQUE,
  stripe_payment_intent_id    TEXT,
  status                      TEXT NOT NULL DEFAULT 'completed'
                              CHECK (status IN ('pending', 'completed', 'refunded', 'failed')),
  created_at                  TEXT NOT NULL DEFAULT (datetime('now')),
  completed_at                TEXT
);

-- ============================================================
-- 6. pf_service_keys
-- ============================================================
-- PebbleFlow-owned OpenRouter credentials provisioned via OAuth flow
-- and scoped per user for metering/attribution. These are NOT
-- user-owned secrets — they are PF service keys held on PF's own
-- OpenRouter account. User-owned provider API keys (BYOA) live
-- on-device and never touch this table.
-- `service_credential` is encrypted at rest with PF_TOKEN_SECRET.
-- ============================================================
CREATE TABLE IF NOT EXISTS pf_service_keys (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider            TEXT NOT NULL DEFAULT 'openrouter',
  service_credential  TEXT NOT NULL,                  -- encrypted at rest with PF_TOKEN_SECRET; see relay/api/crypto.ts
  created_at          TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (user_id, provider)
);

-- ============================================================
-- 7. provisioned_keys (shared pool, no user FK)
-- ============================================================
-- The shared-pool PebbleFlow OpenRouter key(s) that power the free tier
-- across all users. Owned and billed by PebbleFlow on PF's own
-- OpenRouter account. NOT user-owned. `openrouter_key` is encrypted at
-- rest with PF_TOKEN_SECRET via relay/api/crypto.ts → encryptAtRest().
-- ============================================================
CREATE TABLE IF NOT EXISTS provisioned_keys (
  id                  TEXT PRIMARY KEY,
  openrouter_key      TEXT NOT NULL,                 -- encrypted at rest with PF_TOKEN_SECRET; see relay/api/crypto.ts
  name                TEXT,
  is_active           INTEGER NOT NULL DEFAULT 1,
  usage_count         INTEGER NOT NULL DEFAULT 0,
  last_used_at        TEXT,
  daily_request_limit INTEGER NOT NULL DEFAULT 1000,
  requests_today      INTEGER NOT NULL DEFAULT 0,
  limit_reset_at      TEXT,
  created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================================
-- 8. user_devices
-- ============================================================
CREATE TABLE IF NOT EXISTS user_devices (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  license_id    TEXT REFERENCES licenses(id) ON DELETE SET NULL,
  device_id     TEXT NOT NULL,
  device_name   TEXT,
  device_type   TEXT CHECK (device_type IN ('chrome', 'safari', 'electron', 'ios', 'android')),
  is_active     INTEGER NOT NULL DEFAULT 1,
  last_seen_at  TEXT NOT NULL DEFAULT (datetime('now')),
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (user_id, device_id)
);

-- ============================================================
-- 9. revoked_tokens (SOC 2: HIGH-006 / session revocation)
-- ============================================================
CREATE TABLE IF NOT EXISTS revoked_tokens (
  token_hash    TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL,
  revoked_at    TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at    TEXT NOT NULL
);

-- ============================================================
-- 10. audit_logs
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_logs (
  id              TEXT PRIMARY KEY,
  event_type      TEXT NOT NULL,
  user_id         TEXT REFERENCES users(id) ON DELETE SET NULL,
  license_id      TEXT REFERENCES licenses(id) ON DELETE SET NULL,
  subscription_id TEXT REFERENCES subscriptions(id) ON DELETE SET NULL,
  metadata        TEXT NOT NULL DEFAULT '{}',
  ip_address      TEXT,
  user_agent      TEXT,
  created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================================
-- Indexes
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_licenses_user_id        ON licenses(user_id);
CREATE INDEX IF NOT EXISTS idx_licenses_key            ON licenses(license_key);
CREATE INDEX IF NOT EXISTS idx_licenses_stripe_sub     ON licenses(stripe_subscription_id);

CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id   ON subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_stripe_sub ON subscriptions(stripe_subscription_id);

CREATE INDEX IF NOT EXISTS idx_user_provisioned_keys_user ON user_provisioned_keys(user_id);

CREATE INDEX IF NOT EXISTS idx_credit_purchases_user   ON credit_purchases(user_id);

CREATE INDEX IF NOT EXISTS idx_pf_service_keys_user_provider ON pf_service_keys(user_id, provider);

CREATE INDEX IF NOT EXISTS idx_user_devices_user       ON user_devices(user_id);

CREATE INDEX IF NOT EXISTS idx_revoked_tokens_expires   ON revoked_tokens(expires_at);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user         ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_event        ON audit_logs(event_type);

CREATE INDEX IF NOT EXISTS idx_users_google_id         ON users(google_id);
CREATE INDEX IF NOT EXISTS idx_users_stripe_customer   ON users(stripe_customer_id);
