// =============================================================================
// MIRRORED FROM PebbleFlow-ai/PebbleFlow @ 72da4163db8196ce144dc36083f6d338fbee8485
// Source path: cloud/relay/src/api/crypto.ts
// Mirrored at: 2026-04-27T04:51:05Z
//
// This file is auto-generated by the mirror-transparency workflow.
// Do not edit here. Changes must land in the private monorepo first.
// See README.md and ARCHITECTURE.md for the why.
// =============================================================================

/**
 * Server-side Encryption at Rest
 *
 * Provides AES-256-GCM encryption for sensitive data stored in D1.
 * Key is derived from PF_TOKEN_SECRET via HKDF (not the secret directly).
 *
 * Used for: provisioned API keys, shared pool keys.
 * Format: base64url(iv).base64url(ciphertext+tag)
 */

// ============================================================
// Base64url helpers (no padding, URL-safe)
// ============================================================

function uint8ArrayToBase64Url(bytes: Uint8Array): string {
  let binary = ''
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i])
  }
  return btoa(binary)
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '')
}

function base64UrlToUint8Array(base64url: string): Uint8Array {
  const base64 = base64url.replace(/-/g, '+').replace(/_/g, '/')
  const padding = '='.repeat((4 - (base64.length % 4)) % 4)
  const binary = atob(base64 + padding)
  return new Uint8Array(binary.split('').map((c) => c.charCodeAt(0)))
}

// ============================================================
// Key derivation (HKDF from worker secret)
// ============================================================

async function deriveKey(secret: string): Promise<CryptoKey> {
  const encoder = new TextEncoder()
  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    encoder.encode(secret),
    { name: 'HKDF' },
    false,
    ['deriveKey']
  )
  return crypto.subtle.deriveKey(
    {
      name: 'HKDF',
      hash: 'SHA-256',
      salt: encoder.encode('pebbleflow-key-encryption'),
      info: encoder.encode('api-key-at-rest'),
    },
    keyMaterial,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt', 'decrypt']
  )
}

// ============================================================
// Public API
// ============================================================

/**
 * Encrypt a plaintext string for storage in D1.
 * Returns `base64url(iv).base64url(ciphertext)`.
 */
export async function encryptAtRest(plaintext: string, secret: string): Promise<string> {
  const encoder = new TextEncoder()
  const key = await deriveKey(secret)

  const iv = new Uint8Array(12)
  crypto.getRandomValues(iv)

  const ciphertext = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    key,
    encoder.encode(plaintext)
  )

  return `${uint8ArrayToBase64Url(iv)}.${uint8ArrayToBase64Url(new Uint8Array(ciphertext))}`
}

/**
 * Decrypt a value produced by `encryptAtRest`.
 * Throws if the secret is wrong or the ciphertext is tampered.
 */
export async function decryptAtRest(encrypted: string, secret: string): Promise<string> {
  const parts = encrypted.split('.')
  if (parts.length !== 2 || !parts[0] || !parts[1]) {
    throw new Error('Invalid encrypted format: expected iv.ciphertext')
  }

  const iv = base64UrlToUint8Array(parts[0])
  const ciphertext = base64UrlToUint8Array(parts[1])
  const key = await deriveKey(secret)

  const plaintext = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv },
    key,
    ciphertext
  )

  return new TextDecoder().decode(plaintext)
}

/**
 * Check if a string looks like an encrypted value (iv.ciphertext format).
 * Used to distinguish encrypted vs plaintext during migration.
 */
export function isEncryptedAtRest(value: string): boolean {
  const parts = value.split('.')
  if (parts.length !== 2 || !parts[0] || !parts[1]) return false
  // IV should be 12 bytes → 16 base64url chars
  // Ciphertext should be at least a few bytes
  return /^[A-Za-z0-9_-]{16}$/.test(parts[0]) && /^[A-Za-z0-9_-]+$/.test(parts[1])
}
