// =============================================================================
// MIRRORED FROM PebbleFlow-ai/PebbleFlow @ e68ddbef5dd361540b70adb80d961c91a97555c2
// Source path: cloud/relay/src/api/routes/oauth-token.ts
// Mirrored at: 2026-04-27T17:46:27Z
//
// This file is auto-generated by the mirror-transparency workflow.
// Do not edit here. Changes must land in the private monorepo first.
// See README.md and ARCHITECTURE.md for the why.
// =============================================================================

// POST /api/oauth/token - OAuth token exchange proxy
//
// Proxies authorization_code and refresh_token grant requests to OAuth providers,
// injecting the client_secret server-side so it never ships in client code.
//
// Supports multiple client IDs per provider (e.g., Google friction-free + verified-full),
// each with its own Cloudflare Worker secret.
//
// No PF auth required — code exchange happens before login, and refresh tokens
// are credentials in their own right.

import type { Env } from '../../index'
import { errorResponse } from '../types'

/** Supported grant types */
type GrantType = 'authorization_code' | 'refresh_token';

/** A single client registration within a provider */
interface ClientRegistration {
  clientId: string;
  /** Key in Cloudflare env where this client's secret is stored */
  secretEnvKey: string;
}

/** Provider config — token URL and registered client IDs */
interface ProviderConfig {
  tokenUrl: string;
  clients: ClientRegistration[];
}

const OAUTH_PROVIDERS: Record<string, ProviderConfig> = {
  google: {
    tokenUrl: 'https://oauth2.googleapis.com/token',
    clients: [
      {
        clientId: '76300640992-nfqf1bo1caibddoo29u9h92oor7sjlb5.apps.googleusercontent.com',
        secretEnvKey: 'GOOGLE_OAUTH_CLIENT_SECRET',
      },
    ],
  },
  github: {
    tokenUrl: 'https://github.com/login/oauth/access_token',
    clients: [
      {
        clientId: 'Ov23liMl2rAFn9hXG0nI',
        secretEnvKey: 'GITHUB_OAUTH_CLIENT_SECRET',
      },
    ],
  },
  slack: {
    tokenUrl: 'https://slack.com/api/oauth.v2.access',
    clients: [], // TODO: Add Slack client ID once created
  },
}

interface TokenRequestBody {
  provider: string;
  client_id: string;
  grant_type: GrantType;
  code?: string;
  code_verifier?: string;
  redirect_uri?: string;
  refresh_token?: string;
}

export async function handleOAuthToken(request: Request, env: Env): Promise<Response> {
  // 1. Parse JSON body
  let body: TokenRequestBody;
  try {
    body = await request.json() as TokenRequestBody;
  } catch {
    return errorResponse('Invalid JSON body', 400, undefined, request);
  }

  const { provider, client_id, grant_type, code, code_verifier, redirect_uri, refresh_token } = body;

  // 2. Validate provider
  if (!provider || !OAUTH_PROVIDERS[provider]) {
    return errorResponse(`Unknown or missing provider: ${provider}`, 400, undefined, request);
  }

  // 3. Validate client_id
  if (!client_id) {
    return errorResponse('Missing client_id', 400, undefined, request);
  }

  const providerConfig = OAUTH_PROVIDERS[provider];

  // Find the client registration matching the incoming client_id
  const clientReg = providerConfig.clients.find(c => c.clientId === client_id);
  if (!clientReg) {
    return errorResponse(`client_id not allowed for provider ${provider}`, 403, undefined, request);
  }

  // 4. Validate grant_type
  if (grant_type !== 'authorization_code' && grant_type !== 'refresh_token') {
    return errorResponse(`Invalid grant_type: ${grant_type}. Must be authorization_code or refresh_token`, 400, undefined, request);
  }

  // 5. Validate grant-specific fields
  if (grant_type === 'authorization_code') {
    if (!code) {
      return errorResponse('Missing code for authorization_code grant', 400, undefined, request);
    }
    // Require PKCE for authorization_code grants — mitigates authorization code
    // interception attacks. All legitimate clients use PKCE; rejecting requests
    // without code_verifier hardens the proxy against downgrade attacks.
    if (!code_verifier) {
      return errorResponse('Missing code_verifier (PKCE required for authorization_code grant)', 400, 'PKCE_REQUIRED', request);
    }
  }
  if (grant_type === 'refresh_token' && !refresh_token) {
    return errorResponse('Missing refresh_token for refresh_token grant', 400, undefined, request);
  }

  // 6. Look up client_secret from env using this client's secret key
  const clientSecret = (env as unknown as Record<string, string>)[clientReg.secretEnvKey];
  if (!clientSecret) {
    return errorResponse(`Server misconfiguration: secret not set for ${provider}`, 502, undefined, request);
  }

  // 7. Build form-urlencoded body for provider
  const tokenBody: Record<string, string> = {
    client_id,
    client_secret: clientSecret,
    grant_type,
  };

  if (grant_type === 'authorization_code') {
    tokenBody.code = code!;
    tokenBody.code_verifier = code_verifier!;
    if (redirect_uri) tokenBody.redirect_uri = redirect_uri;
  } else {
    tokenBody.refresh_token = refresh_token!;
  }

  // 8. POST to provider token URL
  try {
    const providerResponse = await fetch(providerConfig.tokenUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        // GitHub requires Accept: application/json to return JSON instead of form-urlencoded
        'Accept': 'application/json',
      },
      body: new URLSearchParams(tokenBody),
    });

    // 9. Return raw provider response (preserve status code)
    const responseBody = await providerResponse.text();

    // Verify it's valid JSON before returning
    try {
      JSON.parse(responseBody);
    } catch {
      return errorResponse(`Provider returned non-JSON response`, 502, undefined, request);
    }

    // CORS: Intentionally kept as '*' for OAuth token exchange.
    // OAuth popup windows may have unpredictable origins depending on the
    // provider's redirect flow (Google, GitHub, Slack, Apple). Restricting
    // CORS here would break OAuth for some redirect URI configurations.
    // All other endpoints use origin-specific CORS — see cors.ts.
    return new Response(responseBody, {
      status: providerResponse.status,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
    });
  } catch (err) {
    return errorResponse(
      `Failed to reach ${provider} token endpoint: ${err instanceof Error ? err.message : 'network error'}`,
      502,
      undefined,
      request,
    );
  }
}
