// =============================================================================
// MIRRORED FROM caiioo-ai/caiioo @ 5ed975c29d3a200b1501c4d640d07579f41b7bc9
// Source path: cloud/relay/src/api/routes/oauth-token.ts
// Mirrored at: 2026-09-09T11:01:17Z
//
// This file is auto-generated by the mirror-transparency workflow.
// Do not edit here. Changes must land in the private monorepo first.
// See README.md and ARCHITECTURE.md for the why.
// =============================================================================

// POST /api/oauth/token - OAuth token exchange proxy
//
// Proxies authorization_code and refresh_token grant requests to OAuth providers,
// injecting the client_secret server-side so it never ships in client code.
//
// Supports multiple client IDs per provider (e.g., Google friction-free + verified-full),
// each with its own Cloudflare Worker secret.
//
// AUTH MODEL (C2):
// - authorization_code grants are pre-login (PKCE binds the code), so no
//   bearer is required.
// - refresh_token grants REQUIRE Authorization: Bearer pf_… and the bearer
//   must not be revoked. Without this, anyone with a leaked refresh_token
//   could launder it through our client_secret to mint access tokens.

import type { Env } from '../../index'
import { errorResponse } from '../types'
import { verifyPfToken } from '../pf-token'
import { isTokenRevoked } from './auth-logout'
import { safeAudit } from '../db/queries'
import { generateUUID } from '../uuid'

/** Supported grant types */
type GrantType = 'authorization_code' | 'refresh_token';

/** A single client registration within a provider */
interface ClientRegistration {
  clientId: string;
  /** Key in Cloudflare env where this client's secret is stored */
  secretEnvKey: string;
}

/** Provider config — token URL and registered client IDs */
interface ProviderConfig {
  tokenUrl: string;
  clients: ClientRegistration[];
}

const OAUTH_PROVIDERS: Record<string, ProviderConfig> = {
  google: {
    tokenUrl: 'https://oauth2.googleapis.com/token',
    clients: [
      {
        clientId: '76300640992-nfqf1bo1caibddoo29u9h92oor7sjlb5.apps.googleusercontent.com',
        secretEnvKey: 'GOOGLE_OAUTH_CLIENT_SECRET',
      },
    ],
  },
  github: {
    tokenUrl: 'https://github.com/login/oauth/access_token',
    clients: [
      {
        clientId: 'Ov23liMl2rAFn9hXG0nI',
        secretEnvKey: 'GITHUB_OAUTH_CLIENT_SECRET',
      },
    ],
  },
  // Microsoft (Entra ID) identity sign-in — multi-tenant ("common") app "Caiioo".
  // The code→token exchange returns the id_token the client posts to
  // /api/auth/microsoft. client_secret injected from MICROSOFT_OAUTH_CLIENT_SECRET.
  // clientId kept in sync with CAIIOO_MICROSOFT_AUDIENCES in routes/auth-microsoft.ts
  // (mirrored exactly as google's web client id is).
  microsoft: {
    tokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
    clients: [
      {
        clientId: 'a8628f19-8c1b-4423-9dc8-aac26f10f234',
        secretEnvKey: 'MICROSOFT_OAUTH_CLIENT_SECRET',
      },
    ],
  },
  slack: {
    tokenUrl: 'https://slack.com/api/oauth.v2.access',
    clients: [
      {
        clientId: '11129299368389.11132695954754',
        secretEnvKey: 'SLACK_OAUTH_CLIENT_SECRET',
      },
    ],
  },
  // Slack user-only token endpoint — paired with `oauth/v2_user/authorize`.
  // Same Caiioo Slack app (same client_id + secret), different exchange URL.
  // Used by the mcp.slack.com catalog entry which requests user-token scopes
  // exclusively.
  slack_user: {
    tokenUrl: 'https://slack.com/api/oauth.v2.user.access',
    clients: [
      {
        clientId: '11129299368389.11132695954754',
        secretEnvKey: 'SLACK_OAUTH_CLIENT_SECRET',
      },
    ],
  },
}

interface TokenRequestBody {
  provider: string;
  client_id: string;
  grant_type: GrantType;
  code?: string;
  code_verifier?: string;
  redirect_uri?: string;
  refresh_token?: string;
}

export async function handleOAuthToken(request: Request, env: Env, ctx?: ExecutionContext): Promise<Response> {
  // 1. Parse JSON body
  let body: TokenRequestBody;
  try {
    body = await request.json() as TokenRequestBody;
  } catch {
    return errorResponse('Invalid JSON body', 400, undefined, request);
  }

  const { provider, client_id, grant_type, code, code_verifier, redirect_uri, refresh_token } = body;

  // Diagnostic breadcrumb (no secrets: never log code/verifier/refresh_token).
  // Lets `wrangler tail` distinguish which grant/branch produced an error —
  // status alone can't separate our refresh-grant bearer gate from a mirrored
  // provider rejection.
  console.log('[oauth-token]', provider, grant_type,
    'code:', !!code, 'verifier:', !!code_verifier, 'refresh:', !!refresh_token,
    'redirect:', redirect_uri || '(none)',
    'bearer:', !!(request.headers.get('Authorization') || '').trim());

  // 2. Validate provider
  if (!provider || !OAUTH_PROVIDERS[provider]) {
    return errorResponse(`Unknown or missing provider: ${provider}`, 400, undefined, request);
  }

  // 3. Validate client_id
  if (!client_id) {
    return errorResponse('Missing client_id', 400, undefined, request);
  }

  const providerConfig = OAUTH_PROVIDERS[provider];

  // Find the client registration matching the incoming client_id
  const clientReg = providerConfig.clients.find(c => c.clientId === client_id);
  if (!clientReg) {
    return errorResponse(`client_id not allowed for provider ${provider}`, 403, undefined, request);
  }

  // 4. Validate grant_type
  if (grant_type !== 'authorization_code' && grant_type !== 'refresh_token') {
    return errorResponse(`Invalid grant_type: ${grant_type}. Must be authorization_code or refresh_token`, 400, undefined, request);
  }

  // 5. Validate grant-specific fields
  if (grant_type === 'authorization_code') {
    if (!code) {
      return errorResponse('Missing code for authorization_code grant', 400, undefined, request);
    }
    // Require PKCE for authorization_code grants — mitigates authorization code
    // interception attacks. All legitimate clients use PKCE; rejecting requests
    // without code_verifier hardens the proxy against downgrade attacks.
    if (!code_verifier) {
      return errorResponse('Missing code_verifier (PKCE required for authorization_code grant)', 400, 'PKCE_REQUIRED', request);
    }
  }
  let refreshUserId: string | null = null;
  if (grant_type === 'refresh_token') {
    if (!refresh_token) {
      return errorResponse('Missing refresh_token for refresh_token grant', 400, undefined, request);
    }
    // C2 bearer-auth gate. Code grants stay pre-login (PKCE-bound); refresh
    // grants must prove session, otherwise a leaked refresh_token routes
    // through our client_secret to issue access tokens.
    const authHeader = request.headers.get('Authorization') || '';
    const match = authHeader.match(/^Bearer\s+(.+)$/i);
    if (!match) {
      return errorResponse(
        'Bearer authentication required for refresh_token grant',
        401,
        'AUTH_REQUIRED',
        request
      );
    }
    const bearer = match[1].trim();
    const verified = await verifyPfToken(bearer, env.PF_TOKEN_SECRET);
    if (!verified.valid) {
      return errorResponse('Invalid bearer token', 401, 'INVALID_TOKEN', request);
    }
    if (await isTokenRevoked(env.DB, bearer)) {
      return errorResponse('Bearer token has been revoked', 401, 'TOKEN_REVOKED', request);
    }
    // Kept for the rejection audit below: this grant is bearer-gated, so a
    // refresh failure is attributable to a known user. Code grants are not.
    refreshUserId = verified.payload.sub;
  }

  // 6. Look up client_secret from env using this client's secret key
  const clientSecret = (env as unknown as Record<string, string>)[clientReg.secretEnvKey];
  if (!clientSecret) {
    return errorResponse(`Server misconfiguration: secret not set for ${provider}`, 502, undefined, request);
  }

  // 7. Build form-urlencoded body for provider
  const tokenBody: Record<string, string> = {
    client_id,
    client_secret: clientSecret,
    grant_type,
  };

  if (grant_type === 'authorization_code') {
    tokenBody.code = code!;
    tokenBody.code_verifier = code_verifier!;
    if (redirect_uri) tokenBody.redirect_uri = redirect_uri;
  } else {
    tokenBody.refresh_token = refresh_token!;
  }

  // 8. POST to provider token URL
  try {
    const providerResponse = await fetch(providerConfig.tokenUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        // GitHub requires Accept: application/json to return JSON instead of form-urlencoded
        'Accept': 'application/json',
      },
      body: new URLSearchParams(tokenBody),
    });

    // 9. Return raw provider response (preserve status code)
    const responseBody = await providerResponse.text();

    if (!providerResponse.ok) {
      // Provider error bodies are non-secret ({"error":"invalid_grant",...})
      // and are already returned verbatim to the client below.
      console.log('[oauth-token] provider rejected:', provider, grant_type,
        providerResponse.status, responseBody.slice(0, 300));

      // A refused refresh is the moment a device's credential dies, and it
      // used to survive nowhere: this console line needs a live `wrangler
      // tail` to see, and the device's own log buffer rolls within hours.
      // PF-260907-0002 could not be root-caused for exactly that reason.
      //
      // Only the parsed `error` CODE is stored, never the body. A provider
      // error body is non-secret today, but an audit table is the wrong place
      // to bet on that staying true — a 4xx that echoes the request would
      // carry client_secret and refresh_token straight into it.
      if (grant_type === 'refresh_token') {
        let errorCode: string | undefined;
        try {
          const parsed = JSON.parse(responseBody) as { error?: unknown };
          if (typeof parsed.error === 'string') errorCode = parsed.error;
        } catch {
          // Not JSON (an HTML gateway page, say). The rejection still counts;
          // there is simply no code to record, and none is invented.
        }
        await safeAudit(env.DB, {
          id: generateUUID(),
          event_type: 'oauth.refresh_rejected',
          user_id: refreshUserId,
          metadata: { provider, grant_type, status: providerResponse.status, ...(errorCode ? { error: errorCode } : {}) },
        }, ctx);
      }
    }

    // Verify it's valid JSON before returning
    try {
      JSON.parse(responseBody);
    } catch {
      return errorResponse(`Provider returned non-JSON response`, 502, undefined, request);
    }

    // CORS: Intentionally kept as '*' for OAuth token exchange.
    // OAuth popup windows may have unpredictable origins depending on the
    // provider's redirect flow (Google, GitHub, Slack, Apple). Restricting
    // CORS here would break OAuth for some redirect URI configurations.
    // All other endpoints use origin-specific CORS — see cors.ts.
    return new Response(responseBody, {
      status: providerResponse.status,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
    });
  } catch (err) {
    return errorResponse(
      `Failed to reach ${provider} token endpoint: ${err instanceof Error ? err.message : 'network error'}`,
      502,
      undefined,
      request,
    );
  }
}
