// =============================================================================
// MIRRORED FROM PebbleFlow-ai/PebbleFlow @ c1512946f3f82a38c39f004ba7c04aaae8aa2e38
// Source path: cloud/relay/src/api/routes/openrouter-oauth.ts
// Mirrored at: 2026-04-27T17:53:05Z
//
// This file is auto-generated by the mirror-transparency workflow.
// Do not edit here. Changes must land in the private monorepo first.
// See README.md and ARCHITECTURE.md for the why.
// =============================================================================

// GET /api/oauth/openrouter - OpenRouter PKCE OAuth flow
//
// Actions via query params:
//   ?callback_url=... (default) → Initiate OAuth flow (requires auth)
//   ?code=...&state=...        → Callback from OpenRouter redirect
//   ?action=get_key            → Retrieve stored OAuth key (requires auth)
//   ?action=store_key          → Store an OAuth key (requires auth)
//   ?action=delete_key         → Remove stored OAuth key (requires auth)

import type { Env } from '../../index'
import { requireAuth } from '../auth-middleware'
import { jsonResponse, errorResponse } from '../types'
import { getPFServiceKey, upsertPFServiceKey, deletePFServiceKey, logAudit, safeAudit} from '../db/queries'
import { generateUUID } from '../uuid'
import { encryptAtRest, decryptAtRest, isEncryptedAtRest } from '../crypto'

const OPENROUTER_AUTH_URL = 'https://openrouter.ai/auth'
const OPENROUTER_TOKEN_URL = 'https://openrouter.ai/api/v1/auth/keys'

// State expiry: 10 minutes
const STATE_MAX_AGE_MS = 10 * 60 * 1000

interface OAuthState {
  userId: string
  codeVerifier: string
  callbackUrl: string
  timestamp: number
}

// ============================================================
// PKCE Utilities
// ============================================================

function uint8ArrayToBase64Url(bytes: Uint8Array): string {
  let binary = ''
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i])
  }
  return btoa(binary)
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '')
}

function base64UrlToUint8Array(base64url: string): Uint8Array {
  const base64 = base64url.replace(/-/g, '+').replace(/_/g, '/')
  const padding = '='.repeat((4 - (base64.length % 4)) % 4)
  const binary = atob(base64 + padding)
  return new Uint8Array(binary.split('').map((c) => c.charCodeAt(0)))
}

function generateCodeVerifier(): string {
  const array = new Uint8Array(32)
  crypto.getRandomValues(array)
  return uint8ArrayToBase64Url(array)
}

async function generateCodeChallenge(verifier: string): Promise<string> {
  const encoder = new TextEncoder()
  const data = encoder.encode(verifier)
  const hash = await crypto.subtle.digest('SHA-256', data)
  return uint8ArrayToBase64Url(new Uint8Array(hash))
}

// ============================================================
// AES-GCM state encryption (code_verifier never exposed in URLs)
// ============================================================

async function deriveEncryptionKey(secret: string): Promise<CryptoKey> {
  const encoder = new TextEncoder()
  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    encoder.encode(secret),
    { name: 'HKDF' },
    false,
    ['deriveKey']
  )
  return crypto.subtle.deriveKey(
    {
      name: 'HKDF',
      hash: 'SHA-256',
      salt: encoder.encode('pebbleflow-oauth-state'),
      info: encoder.encode('state-encryption'),
    },
    keyMaterial,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt', 'decrypt']
  )
}

async function encryptState(payload: object, secret: string): Promise<string> {
  const encoder = new TextEncoder()
  const plaintext = encoder.encode(JSON.stringify(payload))
  const key = await deriveEncryptionKey(secret)

  const iv = new Uint8Array(12)
  crypto.getRandomValues(iv)

  const ciphertext = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    key,
    plaintext
  )

  return `${uint8ArrayToBase64Url(iv)}.${uint8ArrayToBase64Url(new Uint8Array(ciphertext))}`
}

async function decryptState<T>(state: string, secret: string): Promise<T | null> {
  try {
    const [ivB64, ctB64] = state.split('.')
    if (!ivB64 || !ctB64) return null

    const iv = base64UrlToUint8Array(ivB64)
    const ciphertext = base64UrlToUint8Array(ctB64)
    const key = await deriveEncryptionKey(secret)

    const plaintext = await crypto.subtle.decrypt(
      { name: 'AES-GCM', iv },
      key,
      ciphertext
    )

    const json = new TextDecoder().decode(plaintext)
    return JSON.parse(json) as T
  } catch (error) {
    console.error('State decryption failed:', error)
    return null
  }
}

// ============================================================
// Redirect helpers
// ============================================================

function errorRedirect(callbackUrl: string | null, message: string): Response {
  if (!callbackUrl) {
    return errorResponse(message, 400)
  }
  const redirectUrl = new URL(callbackUrl)
  redirectUrl.searchParams.set('openrouter_oauth', 'error')
  redirectUrl.searchParams.set('openrouter_oauth_error', message)
  return Response.redirect(redirectUrl.toString(), 303)
}

function successRedirect(callbackUrl: string): Response {
  // Magic value: show inline success page (for extension popup flow)
  if (callbackUrl === '__success_page__') {
    return Response.redirect('https://openrouter.ai/settings/keys', 303)
  }
  const redirectUrl = new URL(callbackUrl)
  redirectUrl.searchParams.set('openrouter_oauth', 'success')
  return Response.redirect(redirectUrl.toString(), 303)
}

// ============================================================
// Main handler
// ============================================================

export async function handleOpenRouterOAuth(request: Request, env: Env, ctx?: ExecutionContext): Promise<Response> {
  const url = new URL(request.url)
  const code = url.searchParams.get('code')
  const state = url.searchParams.get('state')
  const action = url.searchParams.get('action')

  // =========================================================================
  // 1. CALLBACK FLOW (browser redirect from OpenRouter, no auth required)
  // =========================================================================
  if (code && state) {
    try {
      const oauthState = await decryptState<OAuthState>(state, env.PF_TOKEN_SECRET)
      if (!oauthState) {
        return errorRedirect(null, 'Invalid or tampered state parameter.')
      }

      if (Date.now() - oauthState.timestamp > STATE_MAX_AGE_MS) {
        return errorRedirect(oauthState.callbackUrl, 'OAuth session expired. Please try again.')
      }

      // Exchange authorization code for API key
      const tokenResponse = await fetch(OPENROUTER_TOKEN_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          code,
          code_verifier: oauthState.codeVerifier,
          code_challenge_method: 'S256',
        }),
      })

      if (!tokenResponse.ok) {
        const errorText = await tokenResponse.text()
        console.error('OpenRouter token exchange failed:', errorText)
        return errorRedirect(oauthState.callbackUrl, 'Failed to exchange code for API key.')
      }

      const { key } = await tokenResponse.json() as { key?: string }
      if (!key) {
        return errorRedirect(oauthState.callbackUrl, 'OpenRouter did not return an API key.')
      }

      // Encrypt and store the PF-owned service credential in D1.
      // This is a key minted by OpenRouter on PebbleFlow's account via
      // OAuth delegation; not a user-owned credential.
      const encryptedKey = await encryptAtRest(key, env.PF_TOKEN_SECRET)
      await upsertPFServiceKey(env.DB, {
        id: generateUUID(),
        user_id: oauthState.userId,
        provider: 'openrouter',
        service_credential: encryptedKey,
      })

      return successRedirect(oauthState.callbackUrl)
    } catch (err) {
      console.error('OAuth callback error:', err)
      return errorRedirect(null, 'An unexpected error occurred.')
    }
  }

  // =========================================================================
  // All remaining actions require authentication
  // =========================================================================
  const auth = await requireAuth(request, env)
  if (auth instanceof Response) return auth

  // =========================================================================
  // 2. GET KEY (fetch stored OAuth key)
  // =========================================================================
  if (action === 'get_key') {
    // Audit: track usage to confirm this endpoint becomes unused after client migration
    await safeAudit(env.DB, {
      id: generateUUID(),
      event_type: 'oauth_key.get_key',
      user_id: auth.userId,
      ip_address: request.headers.get('CF-Connecting-IP') || 'unknown',
      user_agent: request.headers.get('User-Agent') || 'unknown',
    }, ctx)

    const row = await getPFServiceKey(env.DB, auth.userId, 'openrouter')
    if (!row) {
      return jsonResponse({ key: null, has_key: false }, undefined, undefined, request)
    }
    // Decrypt credential (handles both plaintext pre-migration and encrypted values)
    const decryptedKey = isEncryptedAtRest(row.service_credential)
      ? await decryptAtRest(row.service_credential, env.PF_TOKEN_SECRET)
      : row.service_credential
    return jsonResponse({ key: decryptedKey, has_key: true }, undefined, undefined, request)
  }

  // =========================================================================
  // 3. STORE KEY (client-provided key, no OAuth flow)
  // =========================================================================
  if (action === 'store_key') {
    // Accept from query param or body
    let apiKey = url.searchParams.get('api_key')
    if (!apiKey) {
      try {
        const body = await request.json() as { api_key?: string }
        apiKey = body.api_key ?? null
      } catch {
        // no body
      }
    }
    if (!apiKey) {
      return errorResponse('api_key is required', 400, undefined, request)
    }

    const encryptedApiKey = await encryptAtRest(apiKey, env.PF_TOKEN_SECRET)
    await upsertPFServiceKey(env.DB, {
      id: generateUUID(),
      user_id: auth.userId,
      provider: 'openrouter',
      service_credential: encryptedApiKey,
    })

    // Audit: track usage to confirm this endpoint becomes unused after client migration
    await safeAudit(env.DB, {
      id: generateUUID(),
      event_type: 'oauth_key.store_key',
      user_id: auth.userId,
      ip_address: request.headers.get('CF-Connecting-IP') || 'unknown',
      user_agent: request.headers.get('User-Agent') || 'unknown',
    }, ctx)

    return jsonResponse({ stored: true }, undefined, undefined, request)
  }

  // =========================================================================
  // 4. DELETE KEY
  // =========================================================================
  if (action === 'delete_key') {
    await deletePFServiceKey(env.DB, auth.userId, 'openrouter')
    return jsonResponse({ deleted: true }, undefined, undefined, request)
  }

  // =========================================================================
  // 5. INITIATION FLOW (default: generate auth URL)
  //    Requires callback_url query param
  // =========================================================================
  const callbackUrlParam = url.searchParams.get('callback_url')
  if (!callbackUrlParam) {
    return errorResponse('Missing callback_url parameter.', 400, undefined, request)
  }

  const codeVerifier = generateCodeVerifier()
  const codeChallenge = await generateCodeChallenge(codeVerifier)

  const oauthState: OAuthState = {
    userId: auth.userId,
    codeVerifier,
    callbackUrl: callbackUrlParam,
    timestamp: Date.now(),
  }
  const encryptedState = await encryptState(oauthState, env.PF_TOKEN_SECRET)

  // Build our callback URL (OpenRouter will redirect here)
  const ourCallbackUrl = `${url.origin}/api/oauth/openrouter`

  const authUrl = new URL(OPENROUTER_AUTH_URL)
  authUrl.searchParams.set('callback_url', ourCallbackUrl)
  authUrl.searchParams.set('code_challenge', codeChallenge)
  authUrl.searchParams.set('code_challenge_method', 'S256')
  authUrl.searchParams.set('state', encryptedState)

  return jsonResponse({ url: authUrl.toString() }, undefined, undefined, request)
}
