// =============================================================================
// MIRRORED FROM PebbleFlow-ai/PebbleFlow @ 5c27dc431afd76e4afea4a03f8b023e76eeebcce
// Source path: cloud/relay/src/user-relay.ts
// Mirrored at: 2026-04-27T00:34:28Z
//
// This file is auto-generated by the mirror-transparency workflow.
// Do not edit here. Changes must land in the private monorepo first.
// See README.md and ARCHITECTURE.md for the why.
// =============================================================================

/**
 * User Relay Durable Object
 *
 * Manages WebSocket connections for a single user.
 * Routes messages between the user's server(s) and client devices.
 * Supports multiple server connections with priority-based primary election.
 * Handles E2E encrypted messages (opaque to relay) and key exchange.
 */

import { DurableObject } from 'cloudflare:workers'

// ============================================================================
// Types
// ============================================================================

interface ConnectionMetadata {
  userId: string
  connectionType: 'server' | 'client'
  deviceId: string
  deviceName: string
  serverType?: string
}

interface ServerEntry {
  deviceId: string
  deviceName: string
  priority: number
  connectedAt: number
  lastHeartbeatAt: number // Updated when DO receives PING from this server
}

interface ClientConnection {
  deviceId: string
  deviceName: string
  connectedAt: number
  lastActivity: number
}

interface QueuedMessage {
  payload: string
  sourceDevice: string
  timestamp: number
}

interface KeyExchangeEnvelope {
  version: 1
  type: 'key_exchange'
  publicKey: string
  deviceId: string
  deviceName: string
  timestamp: number
}

// ============================================================================
// Constants
// ============================================================================

const SERVER_PRIORITY: Record<string, number> = { desktop: 10, extension: 5, mobile: 5 }
const DEFAULT_SERVER_PRIORITY = 5

// ============================================================================
// Durable Object
// ============================================================================

export class UserRelay extends DurableObject {
  // Multi-server connections (priority-ranked)
  private servers = new Map<string, ServerEntry>()
  private primaryServerId: string | null = null
  private readonly SERVER_HEALTH_TIMEOUT_MS = 45_000

  // Client connections (mobile apps, web)
  private clients: Map<string, ClientConnection> = new Map()

  // Server's key exchange (for forwarding to new clients — from primary server only)
  private serverKeyExchange: KeyExchangeEnvelope | null = null

  // Message queue for when no server is online
  private messageQueue: QueuedMessage[] = []
  private readonly MAX_QUEUE_SIZE = 100
  private readonly QUEUE_TTL_MS = 5 * 60 * 1000 // 5 minutes

  constructor(ctx: DurableObjectState, env: unknown) {
    super(ctx, env)

    // Auto-respond to PING messages without waking the DO from hibernation.
    // Chrome MV3 service workers go to sleep after ~30s, killing their heartbeat
    // setInterval. Without auto-response, the DO sees no activity and Cloudflare
    // closes the WebSocket with code 1006. This keeps connections alive.
    try {
      this.ctx.setWebSocketAutoResponse(
        new WebSocketRequestResponsePair(
          JSON.stringify({ type: 'PING' }),
          JSON.stringify({ type: 'PONG', timestamp: 0 })
        )
      )
    } catch (error) {
      console.error('[UserRelay] setWebSocketAutoResponse failed:', error)
    }

    // Restore state from storage on wake
    this.ctx.blockConcurrencyWhile(async () => {
      try {
        const [queue, keyExchange] = await Promise.all([
          this.ctx.storage.get<QueuedMessage[]>('messageQueue'),
          this.ctx.storage.get<KeyExchangeEnvelope>('serverKeyExchange'),
        ])

        if (queue) {
          const now = Date.now()
          this.messageQueue = queue.filter(
            (m) => now - m.timestamp < this.QUEUE_TTL_MS
          )
        }

        if (keyExchange) {
          this.serverKeyExchange = keyExchange
        }

      } catch (error) {
        console.error('[UserRelay] Failed to restore state from storage:', error)
      }
    })
  }

  // ============================================================================
  // WebSocket Handling
  // ============================================================================

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url)

    // HTTP POST from Cloudflare Worker — forward to server WebSocket
    if (request.method === 'POST' && url.pathname === '/messaging-webhook') {
      return this.handleWebhookForward(request)
    }

    // WebSocket upgrade — existing behavior
    const metadata: ConnectionMetadata = JSON.parse(
      request.headers.get('X-Connection-Metadata') || '{}'
    )

    // Create WebSocket pair
    const { 0: clientSocket, 1: serverSocket } = new WebSocketPair()

    if (metadata.connectionType === 'server') {
      await this.handleServerConnection(serverSocket, metadata)
    } else {
      await this.handleClientConnection(serverSocket, metadata)
    }

    return new Response(null, { status: 101, webSocket: clientSocket })
  }

  /**
   * Forward a messaging webhook payload to the user's local server.
   * If server is offline, queue the message (existing queue mechanism).
   */
  private async handleWebhookForward(request: Request): Promise<Response> {
    try {
      // M3: Check payload size before parsing
      const contentLength = parseInt(request.headers.get('Content-Length') || '0', 10)
      if (contentLength > 256 * 1024) {
        console.warn(`[UserRelay] Rejecting oversized webhook forward: ${contentLength} bytes`)
        return new Response('Payload too large', { status: 413 })
      }

      const data = await request.json() as Record<string, unknown>

      console.log(`[UserRelay] Webhook forward: servers=${this.servers.size}, primaryId=${this.primaryServerId}, recovering...`)
      const primarySocket = this.getPrimaryServer()
      console.log(`[UserRelay] Webhook forward: primarySocket=${primarySocket ? 'found' : 'null'}, servers after recovery=${this.servers.size}`)

      if (primarySocket && this.primaryServerId) {
        // Send to primary server only — NOT broadcast to all servers.
        // Broadcasting caused duplicate webhook processing when multiple servers
        // (e.g., desktop + extension) were connected simultaneously.
        this.sendToServerById(this.primaryServerId, data)
      } else {
        // Queue for delivery when server reconnects
        console.warn(`[UserRelay] No primary server — queuing webhook (queue size: ${this.messageQueue.length + 1})`)
        this.messageQueue.push({
          payload: JSON.stringify(data),
          sourceDevice: 'webhook',
          timestamp: Date.now(),
        })
        await this.ctx.storage.put('messageQueue', this.messageQueue)
      }

      return new Response('OK', { status: 200 })
    } catch (error) {
      console.error('[UserRelay] Webhook forward error:', error)
      return new Response('Internal error', { status: 500 })
    }
  }

  /**
   * Handle server connection (from user's local machine or extension).
   * Multiple servers can connect simultaneously; primary is elected by priority.
   */
  private async handleServerConnection(
    socket: WebSocket,
    metadata: ConnectionMetadata
  ): Promise<void> {
    const priority = metadata.serverType
      ? (SERVER_PRIORITY[metadata.serverType] ?? DEFAULT_SERVER_PRIORITY)
      : DEFAULT_SERVER_PRIORITY

    // Remove in-memory entry for this device (will be recreated below).
    // Do NOT close old sockets — after Worker deploys, closing stale hibernation
    // sockets can cascade and kill the new socket (code 1006). Let stale sockets
    // die naturally via Cloudflare's idle timeout.
    this.servers.delete(metadata.deviceId)

    const now = Date.now()

    // Accept the WebSocket with tags for identification and hibernation recovery
    this.ctx.acceptWebSocket(socket, ['server', `priority:${priority}`, `device:${metadata.deviceId}`])

    // Create server entry
    const entry: ServerEntry = {
      deviceId: metadata.deviceId,
      deviceName: metadata.deviceName,
      priority,
      connectedAt: now,
      lastHeartbeatAt: now, // Grace period for fresh connections
    }
    this.servers.set(metadata.deviceId, entry)

    // Elect primary (may change if new server has higher priority)
    this.electPrimary()

    // If new server is primary, flush queued messages
    if (this.primaryServerId === metadata.deviceId) {
      await this.flushQueueToServer()
    }

    // Notify all clients that server is connected
    this.broadcastToClients({
      type: 'SERVER_STATUS',
      connected: true,
      connectedAt: now,
    })

    console.log(`[UserRelay] Server connected: ${metadata.deviceId} (type=${metadata.serverType ?? 'unknown'}, priority=${priority}, isPrimary=${this.primaryServerId === metadata.deviceId})`)

    // No keepalive alarm — let the DO hibernate freely. The WebSocket survives
    // hibernation via Cloudflare's Hibernation API. When a webhook arrives, the
    // HTTP POST wakes the DO, getWebSockets('server') recovers the socket, and
    // the message is forwarded. The JSON PING auto-response keeps the socket in
    // hibernation storage without waking the DO.
  }

  /**
   * Handle client connection (mobile app, web)
   */
  private async handleClientConnection(
    socket: WebSocket,
    metadata: ConnectionMetadata
  ): Promise<void> {
    const client: ClientConnection = {
      deviceId: metadata.deviceId,
      deviceName: metadata.deviceName,
      connectedAt: Date.now(),
      lastActivity: Date.now(),
    }

    this.clients.set(metadata.deviceId, client)

    // Accept the WebSocket with tags for identification
    this.ctx.acceptWebSocket(socket, ['client', metadata.deviceId])

    // Send current server status directly on the socket reference
    // (don't use sendToClient — getWebSockets may not find it immediately after accept)
    const primaryEntry = this.primaryServerId ? this.servers.get(this.primaryServerId) : null
    try {
      socket.send(JSON.stringify({
        type: 'SERVER_STATUS',
        connected: this.getPrimaryServer() !== null,
        connectedAt: primaryEntry?.connectedAt ?? null,
      }))
    } catch (error) {
      console.error(`[UserRelay] Failed to send initial status to ${metadata.deviceId}:`, error)
    }

    // If server is connected and has announced its key, send to new client
    if (this.getPrimaryServer() && this.serverKeyExchange) {
      try {
        socket.send(JSON.stringify({
          type: 'KEY_EXCHANGE_RESPONSE',
          keyExchange: this.serverKeyExchange,
        }))
      } catch (error) {
        console.error(`[UserRelay] Failed to send key exchange to ${metadata.deviceId}:`, error)
      }
    }

    // Notify all servers of new client
    if (this.getPrimaryServer()) {
      this.sendToAllServers({
        type: 'CLIENT_CONNECTED',
        deviceId: metadata.deviceId,
        deviceName: metadata.deviceName,
      })
    }

    console.log(`[UserRelay] Client connected: ${metadata.deviceId}`)
  }

  // ============================================================================
  // Message Handling
  // ============================================================================

  /**
   * Called by Cloudflare when WebSocket message received
   */
  async webSocketMessage(
    ws: WebSocket,
    message: string | ArrayBuffer
  ): Promise<void> {
    let tags: string[]
    try {
      tags = this.ctx.getTags(ws)
    } catch {
      // Dead socket after hibernation — ignore
      return
    }
    const isServer = tags.includes('server')

    if (typeof message !== 'string') {
      message = new TextDecoder().decode(message)
    }

    try {
      const data = JSON.parse(message)

      if (isServer) {
        // Restore in-memory server map after hibernation wake-up
        if (this.servers.size === 0) {
          this.recoverServersFromHibernation()
        }
        await this.handleServerMessage(data, ws, tags)
      } else {
        const deviceId = tags.find((t) => t !== 'client') || 'unknown'
        await this.handleClientMessage(data, deviceId)
      }
    } catch (error) {
      console.error('[UserRelay] Message handling error:', error)
    }
  }

  /**
   * Handle message from server
   */
  private async handleServerMessage(
    data: Record<string, unknown>,
    ws: WebSocket,
    tags: string[]
  ): Promise<void> {
    const { type, targetDevice } = data

    switch (type) {
      case 'SERVER_KEY_ANNOUNCE': {
        // Only store key exchange from primary server
        const senderDeviceId = this.findServerDeviceIdByTags(tags)
        if (senderDeviceId === this.primaryServerId) {
          this.serverKeyExchange = data.keyExchange as KeyExchangeEnvelope
          await this.ctx.storage.put('serverKeyExchange', this.serverKeyExchange)
          console.log('[UserRelay] Server key exchange stored (from primary)')
        }
        return
      }

      case 'KEY_EXCHANGE_RESPONSE':
        // Server responding to specific client's key exchange
        if (typeof targetDevice === 'string') {
          this.sendToClient(targetDevice, data)
        }
        return

      case 'KEY_ROTATION_REQUEST':
      case 'KEY_ROTATION_ACK':
        // Key rotation messages - forward to specific client
        if (typeof targetDevice === 'string') {
          this.sendToClient(targetDevice, data)
        }
        return

      case 'ENCRYPTED':
        // Encrypted message to specific client (we can't read it)
        if (typeof targetDevice === 'string') {
          this.sendToClient(targetDevice, {
            type: 'ENCRYPTED',
            payload: data.payload,
          })
        }
        return

      case 'REQUEST_KEY_EXCHANGE':
        // Server asking client to re-key
        if (typeof targetDevice === 'string') {
          this.sendToClient(targetDevice, data)
        }
        return

      case 'BROADCAST':
        // Server broadcasting to all clients (still encrypted per-client)
        // This is just metadata, each message is individually encrypted
        this.broadcastToClients(data.payload as Record<string, unknown>)
        return

      case 'PING': {
        // Server heartbeat — find which server sent it, update health
        const senderDeviceId = this.findServerDeviceIdBySocket(ws)
        if (senderDeviceId) {
          const entry = this.servers.get(senderDeviceId)
          if (entry) {
            entry.lastHeartbeatAt = Date.now()
          }
          // Re-elect in case a previously unhealthy server recovered
          this.electPrimary()
        }
        this.sendToServerSocket(ws, { type: 'PONG', timestamp: Date.now() })
        return
      }

      default:
        console.warn(`[UserRelay] Unknown server message type: ${type}`)
    }
  }

  /**
   * Handle message from client
   */
  private async handleClientMessage(
    data: Record<string, unknown>,
    sourceDevice: string
  ): Promise<void> {
    const { type } = data

    // Update last activity
    const client = this.clients.get(sourceDevice)
    if (client) {
      client.lastActivity = Date.now()
    }

    switch (type) {
      case 'PING':
        // Connection health check
        this.sendToClient(sourceDevice, {
          type: 'PONG',
          timestamp: Date.now(),
        })
        return

      case 'GET_DEVICES':
        // Client requesting list of connected devices
        this.sendToClient(sourceDevice, {
          type: 'CONNECTED_DEVICES',
          devices: this.getConnectedDevices(),
          serverConnected: this.getPrimaryServer() !== null,
        })
        return

      case 'KEY_EXCHANGE':
        // Client sending its public key - forward to server
        if (this.getPrimaryServer()) {
          this.sendToServer({
            type: 'KEY_EXCHANGE',
            sourceDevice,
            payload: data.payload,
          })
        } else {
          this.sendToClient(sourceDevice, {
            type: 'SERVER_DISCONNECTED',
          })
        }
        return

      case 'KEY_ROTATION_REQUEST':
      case 'KEY_ROTATION_ACK':
        // Key rotation messages - forward to server
        if (this.getPrimaryServer()) {
          this.sendToServer({
            type,
            sourceDevice,
            payload: data.payload,
          })
        }
        return

      case 'ENCRYPTED':
        // Encrypted message to server (we can't read it)
        if (this.getPrimaryServer()) {
          this.sendToServer({
            type: 'ENCRYPTED',
            sourceDevice,
            payload: data.payload,
          })
        } else {
          // Queue for later (still encrypted)
          await this.queueMessage(JSON.stringify(data), sourceDevice)
          this.sendToClient(sourceDevice, {
            type: 'MESSAGE_QUEUED',
            queuePosition: this.messageQueue.length,
          })
        }
        return

      default:
        console.warn(`[UserRelay] Unknown client message type: ${type}`)
    }
  }

  // ============================================================================
  // WebSocket Lifecycle
  // ============================================================================

  /**
   * Called by Cloudflare when WebSocket closes
   */
  async webSocketClose(
    ws: WebSocket,
    code: number,
    reason: string
  ): Promise<void> {
    try {
      // After hibernation wake-up on abnormal close (code 1006), getTags() can
      // throw because the WebSocket reference is already dead. Guard with try/catch.
      let tags: string[]
      try {
        tags = this.ctx.getTags(ws)
      } catch (error) {
        console.warn(`[UserRelay] getTags failed on close (code ${code}), checking server state:`, error)
        // Can't determine if this was server or client — check if any server
        // sockets remain via getWebSockets. If fewer than expected, re-recover.
        try {
          const serverSockets = this.ctx.getWebSockets('server')
          if (serverSockets.length === 0) {
            this.servers.clear()
            this.primaryServerId = null
            try {
              this.broadcastToClients({
                type: 'SERVER_STATUS',
                connected: false,
                disconnectedAt: Date.now(),
              })
            } catch { /* clients may also be dead during DO eviction */ }
          } else {
            this.recoverServersFromHibernation()
            this.electPrimary()
          }
        } catch { /* getWebSockets can fail during eviction */ }
        return
      }

      const isServer = tags.includes('server')

      if (isServer) {
        // Find which server disconnected from device tag
        const deviceTag = tags.find(t => t.startsWith('device:'))
        const deviceId = deviceTag?.split(':')[1]

        if (deviceId) {
          this.servers.delete(deviceId)
          console.log(`[UserRelay] Server disconnected: ${deviceId} (code ${code} ${reason})`)

          // If it was primary, re-elect
          if (this.primaryServerId === deviceId) {
            this.primaryServerId = null
            this.electPrimary()

            if (this.primaryServerId) {
              // New primary found — flush queue and notify
              console.log(`[UserRelay] New primary elected: ${this.primaryServerId}`)
              await this.flushQueueToServer()
            }
          }

          // Broadcast status update — wrapped in try/catch because during DO eviction
          // client sockets may also be dead, causing broadcastToClients to throw
          try {
            if (this.servers.size === 0) {
              this.broadcastToClients({
                type: 'SERVER_STATUS',
                connected: false,
                disconnectedAt: Date.now(),
              })
            } else {
              const primaryEntry = this.primaryServerId ? this.servers.get(this.primaryServerId) : null
              this.broadcastToClients({
                type: 'SERVER_STATUS',
                connected: this.primaryServerId !== null,
                connectedAt: primaryEntry?.connectedAt ?? null,
              })
            }
          } catch {
            // Client sockets dead during DO eviction — ignore
          }
        }
      } else {
        const deviceId = tags.find((t) => t !== 'client')
        if (deviceId) {
          this.clients.delete(deviceId)

          // Notify all servers
          if (this.getPrimaryServer()) {
            this.sendToAllServers({
              type: 'CLIENT_DISCONNECTED',
              deviceId,
              timestamp: Date.now(),
            })
          }

          console.log(`[UserRelay] Client disconnected: ${deviceId}`)
        }
      }
    } catch (error) {
      console.error(`[UserRelay] webSocketClose handler failed (code ${code}):`, error)
    }
  }

  /**
   * Called by Cloudflare on WebSocket error
   */
  async webSocketError(ws: WebSocket, error: unknown): Promise<void> {
    console.error('[UserRelay] WebSocket error:', error)
    try {
      ws.close(1011, 'Internal error')
    } catch {
      // Socket already dead after hibernation wake-up — ignore
    }
  }

  // ============================================================================
  // Server Election
  // ============================================================================

  /**
   * Elect the primary server based on priority (highest wins),
   * with connectedAt as tiebreaker (earliest wins).
   * Servers that haven't sent a heartbeat within the health timeout are skipped.
   */
  private electPrimary(): void {
    const now = Date.now()
    let bestId: string | null = null
    let bestPriority = -1
    let bestConnectedAt = Infinity

    for (const [id, entry] of this.servers) {
      // Health check: must have heartbeat within timeout (grace for fresh connections)
      const timeSinceHeartbeat = now - entry.lastHeartbeatAt
      if (timeSinceHeartbeat > this.SERVER_HEALTH_TIMEOUT_MS) continue

      if (entry.priority > bestPriority ||
          (entry.priority === bestPriority && entry.connectedAt < bestConnectedAt)) {
        bestId = id
        bestPriority = entry.priority
        bestConnectedAt = entry.connectedAt
      }
    }

    const oldPrimary = this.primaryServerId
    this.primaryServerId = bestId

    // Notify on primary change
    if (oldPrimary !== bestId) {
      if (oldPrimary) this.sendToServerById(oldPrimary, { type: 'ROLE_CHANGE', role: 'standby' })
      if (bestId) this.sendToServerById(bestId, { type: 'ROLE_CHANGE', role: 'primary' })
      console.log(`[UserRelay] Primary server changed: ${oldPrimary ?? 'none'} -> ${bestId ?? 'none'}`)
    }
  }

  // ============================================================================
  // Server Socket Resolution
  // ============================================================================

  /**
   * Get the primary server's WebSocket, recovering from hibernation if needed.
   * Replaces the old getServerSocket() single-socket method.
   */
  private getPrimaryServer(): WebSocket | null {
    if (!this.primaryServerId) {
      this.recoverServersFromHibernation()
      this.electPrimary()
    }
    if (!this.primaryServerId) return null

    const entry = this.servers.get(this.primaryServerId)
    if (!entry) return null

    // Find the actual socket by device tag. After deploys, multiple stale sockets
    // may exist for the same device. Pick the LAST one (most recently accepted)
    // and verify it's actually usable.
    try {
      const sockets = this.getWebSocketsByTags(['server', `device:${this.primaryServerId}`])
      // Try from newest to oldest — newest is most likely the live one
      for (let i = sockets.length - 1; i >= 0; i--) {
        const s = sockets[i]
        if (s.readyState === 1) return s // 1 = OPEN
      }
      return null
    } catch {
      return null
    }
  }

  /**
   * Recover server entries from hibernation by reading socket tags.
   * In-memory state is lost on hibernation; tags survive.
   */
  private recoverServersFromHibernation(): void {
    let serverSockets: WebSocket[]
    try {
      serverSockets = this.ctx.getWebSockets('server')
    } catch {
      return
    }
    if (serverSockets.length === 0) return

    this.servers.clear()
    for (const socket of serverSockets) {
      try {
        const tags = this.ctx.getTags(socket)
        const priorityTag = tags.find(t => t.startsWith('priority:'))
        const deviceTag = tags.find(t => t.startsWith('device:'))
        const priority = priorityTag ? parseInt(priorityTag.split(':')[1]) : DEFAULT_SERVER_PRIORITY
        const deviceId = deviceTag?.split(':')[1] ?? `recovered-${Date.now()}`

        this.servers.set(deviceId, {
          deviceId,
          deviceName: 'Recovered',
          priority,
          connectedAt: Date.now(),
          lastHeartbeatAt: Date.now(), // Grace period
        })
      } catch { /* dead socket -- skip */ }
    }
    console.log(`[UserRelay] Recovered ${this.servers.size} server(s) from hibernation`)
  }

  /**
   * Find the server deviceId that owns a given WebSocket, by matching tags.
   */
  private findServerDeviceIdByTags(tags: string[]): string | null {
    const deviceTag = tags.find(t => t.startsWith('device:'))
    return deviceTag?.split(':')[1] ?? null
  }

  /**
   * Find the server deviceId that owns a given WebSocket reference.
   * Used when we have the socket but not the tags (e.g., PING handler).
   */
  private findServerDeviceIdBySocket(ws: WebSocket): string | null {
    try {
      const tags = this.ctx.getTags(ws)
      return this.findServerDeviceIdByTags(tags)
    } catch {
      return null
    }
  }

  /**
   * Get WebSockets matching ALL specified tags.
   * CF's getWebSockets() only filters by one tag, so we filter the rest manually.
   */
  private getWebSocketsByTags(tags: string[]): WebSocket[] {
    if (tags.length === 0) return []
    try {
      // Filter by first tag via CF API, then narrow by remaining tags
      const sockets = this.ctx.getWebSockets(tags[0])
      if (tags.length === 1) return sockets
      const remainingTags = tags.slice(1)
      return sockets.filter(socket => {
        try {
          const socketTags = this.ctx.getTags(socket)
          return remainingTags.every(t => socketTags.includes(t))
        } catch {
          return false
        }
      })
    } catch {
      return []
    }
  }

  // ============================================================================
  // Message Queue
  // ============================================================================

  /**
   * Queue a message for when server comes back online
   */
  private async queueMessage(
    payload: string,
    sourceDevice: string
  ): Promise<void> {
    // Remove old messages if queue is full
    while (this.messageQueue.length >= this.MAX_QUEUE_SIZE) {
      this.messageQueue.shift()
    }

    this.messageQueue.push({
      payload,
      sourceDevice,
      timestamp: Date.now(),
    })

    // Persist queue
    await this.ctx.storage.put('messageQueue', this.messageQueue)
  }

  /**
   * Flush queued messages to server (called when server reconnects)
   */
  private async flushQueueToServer(): Promise<void> {
    if (!this.getPrimaryServer() || this.messageQueue.length === 0) return

    const now = Date.now()
    const validMessages = this.messageQueue.filter(
      (m) => now - m.timestamp < this.QUEUE_TTL_MS
    )

    for (const msg of validMessages) {
      const data = JSON.parse(msg.payload)

      // Don't spread queue metadata onto infrastructure messages --
      // MESSAGING_WEBHOOK and similar types have a defined shape that
      // must not be polluted with sourceDevice/wasQueued/timestamp.
      if (data.type === 'MESSAGING_WEBHOOK' && this.primaryServerId) {
        // Send webhooks to primary only (not broadcast) to prevent duplicate processing
        this.sendToServerById(this.primaryServerId, data)
      } else if (data.type === 'MESSAGING_WEBHOOK') {
        // Fallback: no primaryServerId but getPrimaryServer() returned non-null
        // (shouldn't happen, but safe fallback)
        this.sendToServer(data)
      } else {
        this.sendToServer({
          ...data,
          sourceDevice: msg.sourceDevice,
          timestamp: msg.timestamp,
          wasQueued: true,
        })
      }
    }

    // Clear queue
    this.messageQueue = []
    await this.ctx.storage.delete('messageQueue')

    // Notify clients
    this.broadcastToClients({
      type: 'QUEUE_FLUSHED',
      count: validMessages.length,
    })

    console.log(`[UserRelay] Flushed ${validMessages.length} queued messages`)
  }

  // ============================================================================
  // Utility Methods
  // ============================================================================

  /**
   * Send message to primary server
   */
  private sendToServer(data: unknown): void {
    // After hibernation, readyState may show OPEN on zombie sockets.
    // Broadcast to ALL server sockets — the live one receives it,
    // dead ones silently fail (Cloudflare doesn't throw on hibernated sends).
    try {
      const allServerSockets = this.ctx.getWebSockets('server')
      console.log(`[UserRelay] sendToServer: broadcasting to ${allServerSockets.length} server socket(s)`)
      const payload = JSON.stringify(data)
      for (const socket of allServerSockets) {
        try { socket.send(payload) } catch { /* dead socket */ }
      }
    } catch (error) {
      console.error('[UserRelay] Failed to send to server, queuing for retry:', error)
      this.messageQueue.push({
        payload: JSON.stringify(data),
        sourceDevice: 'retry',
        timestamp: Date.now(),
      })
      this.ctx.storage.put('messageQueue', this.messageQueue).catch(e =>
        console.error('[UserRelay] Failed to persist retry queue:', e)
      )
    }
  }

  /**
   * Send message to all connected servers (e.g., CLIENT_CONNECTED/CLIENT_DISCONNECTED)
   */
  private sendToAllServers(data: unknown): void {
    const message = JSON.stringify(data)
    let serverSockets: WebSocket[]
    try {
      serverSockets = this.ctx.getWebSockets('server')
    } catch {
      return
    }

    for (const socket of serverSockets) {
      try {
        socket.send(message)
      } catch (error) {
        console.error('[UserRelay] Failed to send to server socket:', error)
      }
    }
  }

  /**
   * Send message to a specific server by deviceId
   */
  private sendToServerById(deviceId: string, data: unknown): void {
    try {
      const sockets = this.getWebSocketsByTags(['server', `device:${deviceId}`])
      const message = JSON.stringify(data)
      for (const socket of sockets) {
        try {
          socket.send(message)
        } catch (error) {
          console.error(`[UserRelay] Failed to send to server ${deviceId}:`, error)
        }
      }
    } catch {
      // getWebSockets failed — hibernation edge case
    }
  }

  /**
   * Send message directly to a WebSocket reference (e.g., PONG response to specific server)
   */
  private sendToServerSocket(ws: WebSocket, data: unknown): void {
    try {
      ws.send(JSON.stringify(data))
    } catch (error) {
      console.error('[UserRelay] Failed to send to server socket:', error)
    }
  }

  /**
   * Send message to specific client
   */
  private sendToClient(deviceId: string, data: unknown): void {
    // Find the WebSocket for this device
    try {
      const sockets = this.getWebSocketsByTags(['client', deviceId])
      for (const socket of sockets) {
        try {
          socket.send(JSON.stringify(data))
        } catch (error) {
          console.error(`[UserRelay] Failed to send to ${deviceId}:`, error)
        }
      }
    } catch {
      // getWebSockets failed — hibernation edge case
    }
  }

  /**
   * Broadcast message to all clients
   */
  private broadcastToClients(data: unknown): void {
    const message = JSON.stringify(data)
    let sockets: WebSocket[]
    try {
      sockets = this.ctx.getWebSockets('client')
    } catch {
      return
    }

    for (const socket of sockets) {
      try {
        socket.send(message)
      } catch (error) {
        console.error('[UserRelay] Failed to broadcast:', error)
      }
    }
  }

  /**
   * Get list of connected devices
   */
  private getConnectedDevices(): Array<{
    deviceId: string
    deviceName: string
    connectedAt: number
    lastActivity: number
  }> {
    return Array.from(this.clients.values()).map((c) => ({
      deviceId: c.deviceId,
      deviceName: c.deviceName,
      connectedAt: c.connectedAt,
      lastActivity: c.lastActivity,
    }))
  }
}
