// =============================================================================
// MIRRORED FROM PebbleFlow-ai/PebbleFlow @ a6319288558b5fd2b33b0c28d39325a3bc711856
// Source path: src/shared/auth/google-oauth.ts
// Mirrored at: 2026-04-27T04:41:33Z
//
// This file is auto-generated by the mirror-transparency workflow.
// Do not edit here. Changes must land in the private monorepo first.
// See README.md and ARCHITECTURE.md for the why.
// =============================================================================

// =============================================================================
// GOOGLE OAUTH - PebbleFlow user login/authentication
// =============================================================================
//
// PURPOSE: Handles user authentication to sign into PebbleFlow itself.
// This gets an identity token to authenticate the user, NOT to access their data.
//
// This is DISTINCT from connections-manager.ts which handles tool integrations:
// - google-oauth.ts: "Sign in to PebbleFlow with your Google account" (identity only)
// - connections-manager.ts: "Connect your Google account to let the AI read your emails" (API access)
//
// AUTH FLOWS:
// - Extension: Uses chrome.identity.getAuthToken (Chrome profile account)
// - Web/Mobile: Uses popup-based OAuth flow with ID token
//
// SCOPES: Minimal identity scopes only (openid, email, profile)
// No access to Gmail, Drive, Calendar, etc. - that's handled by connections-manager.ts

import type { OAuthCredentials, LoginResponse } from './auth-types';
import { loginWithGoogle } from './auth-client';
import { createOAuthConnection, type OAuthConnection } from '../types/user-profile';
import { PRIVATE_RELAY_BASE_URL, DEFAULT_RELAY_PORT } from '../constants';
import { isNativeAppContext, isNativeMacOS, isBrowserContext, isLocalRelayConnection } from '../runtime-context';
import { logger } from '../logger';
import { generateCodeVerifier, generateCodeChallenge } from '../pkce-utils';
import { exchangeCodeForTokens } from './connections-manager';
import { openExternalUrl } from '../utils/external-url';

// Private relay OAuth callback URL - registered with Google Cloud Console
// This enables OAuth for clients connecting from any network (LAN, remote, etc.)
// The private relay serves an HTML page that extracts tokens and posts them back to the opener
const PRIVATE_RELAY_OAUTH_CALLBACK_URL = `${PRIVATE_RELAY_BASE_URL}/oauth/callback`;

// =============================================================================
// CONFIGURATION
// =============================================================================

/**
 * Google OAuth configuration
 */
export interface GoogleOAuthConfig {
  // OAuth client ID (from Google Cloud Console)
  clientId: string;

  // Scopes for login (minimal - just identity)
  loginScopes?: string[];

  // Redirect URI for web flow
  redirectUri?: string;

  // Use relay for backend calls
  useRelay?: boolean;
}

// Default scopes for login (just identity, not Workspace APIs)
const DEFAULT_LOGIN_SCOPES = [
  'openid',
  'email',
  'profile',
];

let globalConfig: GoogleOAuthConfig | null = null;

/**
 * Configure Google OAuth
 */
export function configureGoogleOAuth(config: GoogleOAuthConfig): void {
  globalConfig = config;
}

/**
 * Get current config
 */
export function getGoogleOAuthConfig(): GoogleOAuthConfig | null {
  return globalConfig;
}

// =============================================================================
// CONTEXT DETECTION
// =============================================================================

/**
 * OAuth context
 */
export type OAuthContext = 'extension' | 'web' | 'native';

/**
 * Check if we're running in actual Google Chrome (not other Chromium browsers).
 * chrome.identity.getAuthToken only works reliably in Google Chrome.
 * Other Chromium browsers (Vivaldi, Brave, Edge, Arc, Opera, etc.) have the API
 * but it doesn't work correctly.
 */
export function isActualChrome(): boolean {
  const ua = navigator.userAgent;

  // These browsers are Chromium-based but NOT Google Chrome
  // chrome.identity.getAuthToken doesn't work on them
  const nonChromeIndicators = [
    'Vivaldi',   // Vivaldi browser
    'Brave',     // Brave browser (may be hidden but often present)
    'Edg/',      // Microsoft Edge (note: "Edg/" not "Edge")
    'OPR/',      // Opera
    'Opera',     // Opera (older versions)
  ];

  // If any non-Chrome indicator is present, it's not real Chrome
  if (nonChromeIndicators.some(indicator => ua.includes(indicator))) {
    logger.debug('[GoogleOAuth] Non-Chrome browser detected via UA:', ua);
    return false;
  }

  // Check userAgentData API first (more reliable and harder to spoof)
  // This is the modern API for browser detection
  if ('userAgentData' in navigator && navigator.userAgentData) {
    const brands = (navigator.userAgentData as { brands?: Array<{ brand: string }> }).brands;
    if (brands) {
      // Vivaldi and other Chromium browsers will NOT have "Google Chrome" in brands
      // They'll have "Chromium" or their own brand name
      const hasGoogleChrome = brands.some(b => b.brand === 'Google Chrome');
      const hasVivaldi = brands.some(b => b.brand === 'Vivaldi');
      const hasBrave = brands.some(b => b.brand === 'Brave');
      const hasEdge = brands.some(b => b.brand === 'Microsoft Edge');

      if (hasVivaldi || hasBrave || hasEdge) {
        logger.debug('[GoogleOAuth] Non-Chrome browser detected via userAgentData:', brands.map(b => b.brand).join(', '));
        return false;
      }

      if (!hasGoogleChrome) {
        logger.debug('[GoogleOAuth] Google Chrome brand not found in userAgentData:', brands.map(b => b.brand).join(', '));
        return false;
      }
    }
  }

  // Must have "Chrome/" in UA to be Chrome
  if (!ua.includes('Chrome/')) {
    return false;
  }

  return true;
}

/**
 * Detect current OAuth context
 * Must distinguish real Chrome extension from Chrome API stub (used in WKWebView/relay)
 * and from non-Chrome Chromium browsers where chrome.identity doesn't work
 */
export function detectOAuthContext(): OAuthContext {
  // Native app (iOS or Android) - uses platform-specific OAuth via native bridge.
  // macOS uses web OAuth via the relay server (not the native bridge) because
  // ASWebAuthenticationSession opens the system default browser which may not be Safari.
  if (isNativeAppContext() && !isNativeMacOS()) {
    return 'native';
  }

  // Check for Chromium extension context with launchWebAuthFlow support:
  // - chrome.runtime.id is only present in actual extensions, not in our Chrome stub
  // - launchWebAuthFlow works in ALL Chromium browsers (Chrome, Vivaldi, Brave, Edge, etc.)
  // - We use launchWebAuthFlow (not getAuthToken) for login, so no Chrome-only restriction needed
  // - The isActualChrome() guard was wrong here — it blocked non-Chrome browsers from using
  //   launchWebAuthFlow, forcing them into a broken window.open() popup path
  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
  if (typeof chrome !== 'undefined' &&
      chrome.runtime?.id &&
      chrome.identity &&
      typeof chrome.identity.launchWebAuthFlow === 'function') {
    return 'extension';
  }
  return 'web';
}

// =============================================================================
// iOS NATIVE OAUTH (ASWebAuthenticationSession via native bridge)
// =============================================================================

/**
 * iOS OAuth client ID (iOS application type, public client with PKCE).
 * The reversed client ID serves as the custom URL scheme for ASWebAuthenticationSession.
 */
const IOS_GOOGLE_CLIENT_ID = '298885654087-pqhd75moiiju7ogfrpmguc9c00a6e3ej.apps.googleusercontent.com';
const IOS_CALLBACK_URL_SCHEME = 'com.googleusercontent.apps.298885654087-pqhd75moiiju7ogfrpmguc9c00a6e3ej';

/** Full OAuth result from the iOS native bridge, stored for connection creation. */
export interface IOSOAuthResult {
  accessToken: string;
  refreshToken?: string;
  expiresIn?: number;
  email: string;
  name: string;
  picture?: string;
  sub: string;
  /** Scopes that were actually requested in this OAuth flow.
   *  Used by autoCreateGoogleConnection to record what the token is authorized for,
   *  rather than relying on PROVIDER_REGISTRY.google.defaultScopes staying in sync. */
  grantedScopes?: string[];
}

/**
 * Last iOS OAuth result, stored so PebbleFlowAuth.autoCreateGoogleConnection()
 * can create a connection with a real token instead of a placeholder.
 */
let lastIOSOAuthResult: IOSOAuthResult | null = null;

/**
 * Set the last iOS/Android OAuth result directly.
 * Used by the OAuth recovery path when the native side completed the token
 * exchange after activity recreation.
 */
export function setLastIOSOAuthResult(result: IOSOAuthResult): void {
  lastIOSOAuthResult = result;
}

/**
 * Consume the last iOS OAuth result (returns and clears it).
 * Used by PebbleFlowAuth to create a Google connection with real tokens.
 */
export function consumeLastIOSOAuthResult(): IOSOAuthResult | null {
  const r = lastIOSOAuthResult;
  lastIOSOAuthResult = null;
  return r;
}

/** OAuth result from extension login, stored for autoCreateGoogleConnection. */
export interface ExtensionOAuthResult {
  accessToken: string;
  refreshToken?: string;
  expiresIn?: number;
  email?: string;
  name?: string;
  grantedScopes?: string[];
}

/**
 * Last extension OAuth result, stored so PebbleFlowAuth.autoCreateGoogleConnection()
 * can reuse login tokens instead of triggering a second OAuth popup via getAuthToken.
 */
let lastExtensionOAuthResult: ExtensionOAuthResult | null = null;

/**
 * Consume the last extension OAuth result (returns and clears it).
 * Used by PebbleFlowAuth to create a Google connection with real tokens.
 */
export function consumeLastExtensionOAuthResult(): ExtensionOAuthResult | null {
  const r = lastExtensionOAuthResult;
  lastExtensionOAuthResult = null;
  return r;
}

/**
 * Get Google access token via native bridge (iOS or Android).
 *
 * iOS: ASWebAuthenticationSession with iOS-specific PKCE client ID.
 * Android: Chrome Custom Tabs with Android-specific PKCE redirect through Cloudflare relay.
 *
 * Both platforms handle PKCE generation, browser session, code exchange natively
 * and return the access token. The token is then sent to PebbleFlow Cloud
 * auth-google edge function for session creation.
 *
 * Requests ONLY identity scopes (openid, email, profile) — the minimum needed to
 * authenticate the user. Workspace scopes (Calendar, Gmail, Drive, etc.) are requested
 * just-in-time via incremental authorization when tools actually need them.
 */
async function getNativeGoogleToken(): Promise<{
  accessToken: string;
} | null> {
  const { callNative } = await import('../native-app/bridge');
  const { GOOGLE_IDENTITY_SCOPES } = await import('./connections-manager');

  const requestedScopes = [...GOOGLE_IDENTITY_SCOPES];

  // Both platforms use the same bridge action. Android's AuthChannel.kt ignores
  // the iOS client ID/callback scheme and uses its own Web OAuth client ID
  // with an HTTPS redirect through the Cloudflare relay.
  const result = await callNative<IOSOAuthResult>(
    'auth',
    'startGoogleOAuth',
    [IOS_GOOGLE_CLIENT_ID, IOS_CALLBACK_URL_SCHEME, requestedScopes.join(' ')],
  );

  if (!result?.accessToken) return null;

  // Record the scopes that were requested so autoCreateGoogleConnection
  // stores accurate scope metadata on the connection.
  result.grantedScopes = requestedScopes;
  lastIOSOAuthResult = result;
  return { accessToken: result.accessToken };
}

// getIOSGoogleToken removed — use getNativeGoogleToken() which handles both iOS and Android.

// =============================================================================
// EXTENSION OAUTH (chrome.identity)
// =============================================================================

/**
 * Get Google ID token using chrome.identity.launchWebAuthFlow
 *
 * IMPORTANT: chrome.identity.getAuthToken() returns ACCESS tokens (for API calls),
 * not ID tokens (for authentication). For login, we need an ID token.
 *
 * launchWebAuthFlow does the full OAuth flow and returns both tokens:
 * - Uses chromiumapp.org redirect URI (Chrome handles this specially)
 * - Returns ID token + access token in URL fragment
 * - Works with Chrome profile account by default
 *
 * @param interactive - Show OAuth consent screen if needed
 * @param forceAccountSelection - Force account picker even if already logged in
 */
async function getExtensionGoogleToken(
  interactive: boolean = true,
  forceAccountSelection: boolean = false
): Promise<{
  accessToken: string;
  idToken?: string;
  email?: string;
  name?: string;
} | null> {
  if (typeof chrome === 'undefined' || !chrome?.identity?.launchWebAuthFlow) {
    throw new Error('Chrome Identity API not available');
  }

  const config = getGoogleOAuthConfig();
  if (!config?.clientId) {
    throw new Error('Google OAuth not configured - missing clientId');
  }

  // Use chrome.identity.getRedirectURL() for the chromiumapp.org redirect
  // This is a special Chrome-handled URL that launchWebAuthFlow intercepts
  const redirectUri = chrome.identity.getRedirectURL();

  // PKCE: Generate code verifier + challenge for secure authorization code flow
  const codeVerifier = generateCodeVerifier();
  const codeChallenge = await generateCodeChallenge(codeVerifier);

  const params = new URLSearchParams({
    client_id: config.clientId,
    redirect_uri: redirectUri,
    response_type: 'code',
    scope: (config.loginScopes ?? DEFAULT_LOGIN_SCOPES).join(' '),
    code_challenge: codeChallenge,
    code_challenge_method: 'S256',
    access_type: 'offline',
    // Only force account selection if requested, otherwise use Chrome profile
    ...(forceAccountSelection ? { prompt: 'select_account' } : {}),
  });

  const authUrl = `https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`;
  logger.info('[GoogleOAuth] Starting launchWebAuthFlow with PKCE (code flow)');

  return new Promise((resolve, reject) => {
    chrome.identity.launchWebAuthFlow(
      {
        url: authUrl,
        interactive,
      },
      async (redirectUrl) => {
        if (chrome.runtime.lastError) {
          // User closed the popup or denied access
          if (chrome.runtime.lastError.message?.includes('canceled') ||
              chrome.runtime.lastError.message?.includes('closed')) {
            reject(new Error('Sign in was cancelled'));
          } else {
            reject(new Error(chrome.runtime.lastError.message || 'OAuth failed'));
          }
          return;
        }

        if (!redirectUrl) {
          resolve(null);
          return;
        }

        // Extract authorization code from query params (code flow uses ?code=xxx, not fragment)
        try {
          const url = new URL(redirectUrl);
          const code = url.searchParams.get('code');
          const error = url.searchParams.get('error');

          if (error) {
            reject(new Error(`OAuth error: ${error}`));
            return;
          }

          if (!code) {
            reject(new Error('No authorization code received from OAuth'));
            return;
          }

          // Exchange authorization code for tokens via relay (secret injected server-side)
          logger.debug('[GoogleOAuth] Exchanging authorization code for tokens...');
          const tokens = await exchangeCodeForTokens('google', code, codeVerifier, redirectUri, config.clientId);

          // Decode ID token to get user info (it's a JWT)
          let email: string | undefined;
          let name: string | undefined;

          if (tokens.idToken) {
            try {
              const payload = JSON.parse(atob(tokens.idToken.split('.')[1]));
              email = payload.email;
              name = payload.name;
              logger.debug('[GoogleOAuth] Decoded ID token, email:', email);
            } catch (decodeError) {
              logger.warn('[GoogleOAuth] Failed to decode ID token:', decodeError);
            }
          }

          // Store for autoCreateGoogleConnection to reuse (avoids second OAuth popup)
          lastExtensionOAuthResult = {
            accessToken: tokens.accessToken,
            refreshToken: tokens.refreshToken,
            expiresIn: tokens.expiresIn,
            email,
            name,
            grantedScopes: [...DEFAULT_LOGIN_SCOPES],
          };

          resolve({
            accessToken: tokens.accessToken,
            idToken: tokens.idToken,
            email,
            name,
          });
        } catch (parseError) {
          reject(parseError instanceof Error ? parseError : new Error('Failed to exchange authorization code'));
        }
      }
    );
  });
}

/**
 * Get Google token with account selection - uses launchWebAuthFlow with prompt=select_account
 * This is just a convenience wrapper that calls the main function with forceAccountSelection=true
 */
async function getExtensionGoogleTokenWithAccountSelection(): Promise<{
  accessToken: string;
  idToken?: string;
  email?: string;
  name?: string;
} | null> {
  return getExtensionGoogleToken(true, true);
}

/**
 * Fetch Google user info from access token
 */
async function fetchGoogleUserInfo(
  accessToken: string
): Promise<{ email: string; name: string; picture?: string; sub: string }> {
  const response = await fetch('https://www.googleapis.com/oauth2/v3/userinfo', {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch user info: ${response.status}`);
  }

  return response.json();
}

// =============================================================================
// WEB OAUTH (popup or redirect flow)
// =============================================================================

/**
 * Get the appropriate OAuth redirect URI for popup-based web OAuth flow.
 *
 * IMPORTANT: This function is for popup-based OAuth (window.open), NOT for
 * chrome.identity.launchWebAuthFlow(). The chromiumapp.org redirect URLs
 * only work with launchWebAuthFlow - they are NOT real DNS domains.
 *
 * For popup-based OAuth, we always use the private relay URL because:
 * 1. Google redirects to private relay with tokens in URL fragment
 * 2. Private relay serves an HTML page that extracts tokens
 * 3. HTML page posts tokens back to the opener window via postMessage
 * 4. The opener (PebbleFlow client) receives tokens and completes auth
 *
 * This works for ANY client (extension, web, relay) from ANY network.
 */
function getOAuthRedirectUri(config: GoogleOAuthConfig | null): string {
  // If explicitly configured, use that
  if (config?.redirectUri) {
    return config.redirectUri;
  }

  // When the UI is served by a local relay (Tauri sidepanel, macOS WKWebView on
  // localhost, web UI served by the local relay), the callback MUST target the
  // local server so its /oauth/callback page can broadcast the tokens to the
  // connected WebSocket client. The cloud relay callback can't reach local
  // WebSocket subscribers unless a private relay tunnel is set up — which is
  // not the default for Tauri/Linux.
  //
  // Google Cloud Console already has `http://localhost:3847/oauth/callback`
  // registered for the web/desktop OAuth client.
  if (isLocalRelayConnection()) {
    const port = (isBrowserContext() && window.location?.port) || `${DEFAULT_RELAY_PORT}`;
    return `http://localhost:${port}/oauth/callback`;
  }

  // Extension / private-relay-connected contexts: use the cloud callback.
  // The private relay's callback page broadcasts via the same WebSocket the
  // extension/native app is subscribed to.
  //
  // NOTE: chrome.identity.getRedirectURL() returns chromiumapp.org which
  // is NOT a real domain - it only works with chrome.identity.launchWebAuthFlow().
  // Since we use popup-based OAuth (window.open), we need a real URL.
  return PRIVATE_RELAY_OAUTH_CALLBACK_URL;
}

/**
 * Detect if we need to open OAuth in a system browser instead of a popup.
 * True for: native apps (iOS WKWebView, Android WebView), Tauri, macOS WKWebView on localhost.
 */
function isWKWebView(): boolean {
  // Native app WebView can't do popup OAuth — must use system browser
  if (isNativeAppContext()) return true;

  // Tauri desktop app — webview can't do popup OAuth, must use system browser
  if (isBrowserContext() && (window as any).__TAURI__) return true;

  // macOS native sidepanel (WKWebView on localhost) — must use system browser
  if (isLocalRelayConnection() && isNativeMacOS()) return true;

  return false;
}

/**
 * Open URL in the system browser via the cross-platform openExternalUrl abstraction.
 * Handles WKWebView (webkit messageHandlers), Tauri (plugin-shell), extension
 * (chrome.tabs), and browser (window.open) contexts automatically.
 */
function openInSystemBrowser(url: string): void {
  openExternalUrl(url).catch((e: Error) => {
    logger.error('[GoogleOAuth] Failed to open URL externally:', e);
  });
}

/**
 * Initiate web OAuth flow using popup or redirect
 */
async function getWebGoogleToken(): Promise<{
  idToken: string;
  accessToken?: string;
  email?: string;
  name?: string;
} | null> {
  const config = getGoogleOAuthConfig();
  logger.debug('[GoogleOAuth] getWebGoogleToken called, config:', config ? 'present' : 'null');

  if (!config?.clientId) {
    throw new Error('Google OAuth not configured - missing clientId');
  }

  const redirectUri = getOAuthRedirectUri(config);
  logger.debug('[GoogleOAuth] Redirect URI:', redirectUri);

  // PKCE: Generate code verifier + challenge for secure authorization code flow
  const codeVerifier = generateCodeVerifier();
  const codeChallenge = await generateCodeChallenge(codeVerifier);

  // Build state parameter with opener origin and local relay URL
  // - openerOrigin: Used by callback page as postMessage target origin
  //   (critical for non-Chrome browsers where origin is chrome-extension://)
  // - relayUrl: Fallback redirect when postMessage isn't available
  //   (e.g., WKWebView opens Safari, which can't postMessage back to WKWebView)
  const stateData: Record<string, string> = {};
  if (isBrowserContext() && window.location) {
    stateData.openerOrigin = window.location.origin;
    const protocol = window.location.protocol === 'https:' ? 'https' : 'http';
    const host = window.location.host;
    stateData.relayUrl = `${protocol}://${host}`;
  }
  const state = encodeURIComponent(JSON.stringify(stateData));

  const params = new URLSearchParams({
    client_id: config.clientId,
    redirect_uri: redirectUri,
    response_type: 'code',
    scope: (config.loginScopes ?? DEFAULT_LOGIN_SCOPES).join(' '),
    code_challenge: codeChallenge,
    code_challenge_method: 'S256',
    access_type: 'offline',
    state: state,
    prompt: 'select_account',
  });

  const authUrl = `https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`;
  logger.debug('[GoogleOAuth] Auth URL built (PKCE code flow), isWKWebView:', isWKWebView());

  return new Promise((resolve, reject) => {
    // For WKWebView, open in system browser
    if (isWKWebView()) {
      logger.debug('[GoogleOAuth] WKWebView detected, calling openInSystemBrowser');
      openInSystemBrowser(authUrl);
      logger.debug('[GoogleOAuth] openInSystemBrowser called, now waiting for callback...');

      // Listen for callback via window message events
      // The relay server broadcasts OAUTH_CALLBACK_RESULT which transport.ts forwards
      let resolved = false;

      const cleanup = () => {
        resolved = true;
        window.removeEventListener('message', handleMessage);
        window.removeEventListener('pebbleflow-oauth-result', handleCustomEvent as EventListener);
      };

      // Exchange authorization code for tokens (shared helper for all WKWebView message paths)
      const exchangeCode = async (code: string) => {
        try {
          const tokens = await exchangeCodeForTokens('google', code, codeVerifier, redirectUri, config!.clientId);
          let email: string | undefined;
          let name: string | undefined;
          if (tokens.idToken) {
            try {
              const payload = JSON.parse(atob(tokens.idToken.split('.')[1]));
              email = payload.email;
              name = payload.name;
            } catch { /* token decode failure is non-fatal */ }
          }
          resolve({ idToken: tokens.idToken || '', accessToken: tokens.accessToken, email, name });
        } catch (err) {
          reject(err instanceof Error ? err : new Error('Failed to exchange authorization code'));
        }
      };

      // Handle messages (from transport layer or postMessage)
      const handleMessage = (event: MessageEvent) => {
        if (resolved) return;

        // Handle postMessage from popup/callback page (code flow)
        if (event.data?.type === 'google-oauth-callback') {
          cleanup();
          if (event.data.error) {
            reject(new Error(event.data.error));
          } else if (event.data.code) {
            exchangeCode(event.data.code);
          } else {
            reject(new Error('No authorization code in callback'));
          }
          return;
        }

        // Handle OAUTH_CALLBACK_RESULT from relay server (via transport or oauth-broadcast)
        if (event.data?.type === 'OAUTH_CALLBACK_RESULT') {
          // Support both wrapped (payload) and flat formats
          const payload = event.data.payload || event.data;
          logger.debug('[GoogleOAuth] Received OAuth result via transport');
          cleanup();
          if (payload.error) {
            reject(new Error(payload.error));
          } else if (payload.code) {
            exchangeCode(payload.code);
          } else {
            reject(new Error('No authorization code in callback'));
          }
        }
      };

      // Also listen for custom event (dispatched by transport layer)
      const handleCustomEvent = (event: CustomEvent) => {
        if (resolved) return;
        const payload = event.detail;
        if (payload) {
          logger.debug('[GoogleOAuth] Received OAuth result via custom event');
          cleanup();
          if (payload.error) {
            reject(new Error(payload.error));
          } else if (payload.code) {
            exchangeCode(payload.code);
          } else {
            reject(new Error('No authorization code in callback'));
          }
        }
      };

      window.addEventListener('message', handleMessage);
      window.addEventListener('pebbleflow-oauth-result', handleCustomEvent as EventListener);

      // Timeout after 5 minutes
      setTimeout(() => {
        if (!resolved) {
          cleanup();
          reject(new Error('OAuth timeout'));
        }
      }, 5 * 60 * 1000);

      return;
    }

    // Standard popup flow for browsers
    logger.debug('[GoogleOAuth] Opening popup for OAuth flow, origin:', window.location.origin);
    const popup = window.open(
      authUrl,
      'google-oauth',
      'width=500,height=600,scrollbars=yes'
    );

    logger.debug('[GoogleOAuth] window.open() returned:', popup ? 'Window object' : 'null/undefined',
      popup ? `closed=${popup.closed}` : '');

    if (!popup || popup.closed) {
      // Popup blocked - reject with clear error instead of navigating away
      // (navigating the sidepanel to Google destroys the app)
      logger.warn('[GoogleOAuth] Popup blocked by browser');
      reject(new Error('Popup blocked — please allow popups for this extension and try again'));
      return;
    }

    // Shared cleanup for all exit paths
    let popupMonitor: ReturnType<typeof setInterval>;
    const cleanup = () => {
      clearInterval(popupMonitor);
      window.removeEventListener('message', handleMessage);
      try { popup.close(); } catch { /* COOP violation - ignore */ }
    };

    // Exchange authorization code for tokens (shared helper for popup message paths)
    const exchangeCodePopup = async (code: string) => {
      try {
        const tokens = await exchangeCodeForTokens('google', code, codeVerifier, redirectUri, config!.clientId);
        let email: string | undefined;
        let name: string | undefined;
        if (tokens.idToken) {
          try {
            const payload = JSON.parse(atob(tokens.idToken.split('.')[1]));
            email = payload.email;
            name = payload.name;
          } catch { /* token decode failure is non-fatal */ }
        }
        resolve({ idToken: tokens.idToken || '', accessToken: tokens.accessToken, email, name });
      } catch (err) {
        reject(err instanceof Error ? err : new Error('Failed to exchange authorization code'));
      }
    };

    // Listen for callback message
    // Accept messages from current origin, localhost, or private relay
    const handleMessage = (event: MessageEvent) => {
      logger.debug('[GoogleOAuth] postMessage received, origin:', event.origin, 'type:', event.data?.type);

      const isCurrentOrigin = event.origin === window.location.origin;
      const isLocalhost = event.origin.startsWith('http://localhost:');
      const isPrivateRelay = event.origin === PRIVATE_RELAY_BASE_URL;

      if (!isCurrentOrigin && !isLocalhost && !isPrivateRelay) {
        logger.debug('[GoogleOAuth] Ignoring message from unrecognized origin:', event.origin,
          '(expected:', window.location.origin, 'or', PRIVATE_RELAY_BASE_URL, ')');
        return;
      }

      // Handle message from private relay (OAUTH_CALLBACK_RESULT format — code flow)
      if (event.data?.type === 'OAUTH_CALLBACK_RESULT') {
        logger.debug('[GoogleOAuth] Received OAUTH_CALLBACK_RESULT, success:', event.data.success);
        cleanup();

        if (!event.data.success || event.data.error) {
          reject(new Error(event.data.error || 'OAuth failed'));
        } else if (event.data.code) {
          exchangeCodePopup(event.data.code);
        } else {
          reject(new Error('No authorization code in OAuth callback'));
        }
        return;
      }

      // Handle legacy format (google-oauth-callback)
      if (event.data?.type === 'google-oauth-callback') {
        logger.debug('[GoogleOAuth] Received google-oauth-callback');
        cleanup();

        if (event.data.error) {
          reject(new Error(event.data.error));
        } else if (event.data.code) {
          exchangeCodePopup(event.data.code);
        } else {
          reject(new Error('No authorization code in OAuth callback'));
        }
      }
    };

    window.addEventListener('message', handleMessage);

    // Monitor popup — detect if user closes it without completing OAuth
    popupMonitor = setInterval(() => {
      try {
        if (popup.closed) {
          logger.debug('[GoogleOAuth] Popup was closed without completing OAuth');
          cleanup();
          reject(new Error('Sign in was cancelled'));
        }
      } catch {
        // Cross-origin access error — popup is still open, just can't read .closed
      }
    }, 1000);

    // Timeout after 5 minutes
    setTimeout(() => {
      cleanup();
      reject(new Error('OAuth timeout'));
    }, 5 * 60 * 1000);
  });
}

// =============================================================================
// UNIFIED LOGIN FLOW
// =============================================================================

/**
 * Login with Google - unified flow for extension, web, and iOS
 *
 * All contexts get Google OAuth tokens via their platform-specific method,
 * then send them to the PebbleFlow Cloud auth-google edge function for session creation.
 *
 * @param options.interactive - Show OAuth consent screen if needed (default: true)
 * @param options.forceAccountSelection - Allow user to choose any Google account, not just Chrome profile (default: false)
 * @param options.useRelay - Use relay server for backend calls
 */
export async function loginWithGoogleOAuth(options?: {
  interactive?: boolean;
  forceAccountSelection?: boolean;
  useRelay?: boolean;
  createIfNotExists?: boolean;
}): Promise<LoginResponse> {
  const context = detectOAuthContext();
  const config = getGoogleOAuthConfig();

  try {
    // All platforms (macOS, iOS, Android, Chrome extension, Tauri, web) share the same flow:
    //   1. Get Google tokens (platform-specific: native OAuth / chrome.identity / system browser)
    //   2. Call loginWithGoogle(credentials) which hits cloud /api/auth/google
    //   3. Caller runs syncLicenseFromServer to apply the user-tier floor rule from /api/auth/me
    //
    // Tauri falls through to the web flow below: isWKWebView() returns true for Tauri,
    // so getWebGoogleToken() opens the system browser and waits for the callback page
    // to broadcast OAUTH_CALLBACK_RESULT via WebSocket (transport.ts forwards it as a
    // 'pebbleflow-oauth-result' custom event).
    let credentials: OAuthCredentials | null = null;
    let usedChromeIdentity = false;

    if (context === 'native') {
      // Native app (iOS/Android) - platform-specific OAuth via native bridge
      // Gets Google access token, then PebbleFlow Cloud handles session creation
      const tokenInfo = await getNativeGoogleToken();
      if (!tokenInfo) {
        return {
          success: false,
          error: { code: 'invalid_token', message: 'Failed to get Google token from native app' },
        };
      }
      credentials = {
        method: 'google',
        accessToken: tokenInfo.accessToken,
      };
      logger.debug('[GoogleOAuth] Got credentials from native OAuth');
    } else if (context === 'extension') {
      // Extension flow - try chrome.identity first
      // This may fail on non-Chrome browsers (Vivaldi, Brave, Edge, etc.) that have
      // the chrome.identity API but don't fully support it
      try {
        const tokenInfo = await getExtensionGoogleToken(
          options?.interactive ?? true,
          options?.forceAccountSelection ?? false
        );

        if (tokenInfo) {
          // launchWebAuthFlow returns both idToken and accessToken
          // Use idToken for authentication (backend validates with PebbleFlow Cloud signInWithIdToken)
          credentials = {
            method: 'google',
            idToken: tokenInfo.idToken, // Real ID token from launchWebAuthFlow
            accessToken: tokenInfo.accessToken,
          };
          usedChromeIdentity = true;
          logger.debug('[GoogleOAuth] Got credentials from chrome.identity launchWebAuthFlow, idToken:', !!tokenInfo.idToken);
        }
      } catch (extensionError) {
        // chrome.identity failed - this is expected on non-Chrome browsers
        // Log and fall through to web OAuth
        logger.warn('[GoogleOAuth] chrome.identity failed, falling back to web OAuth:', extensionError);
      }
    }

    // Use web flow if:
    // 1. We're in web context, OR
    // 2. Extension flow failed/returned no credentials (non-Chrome browsers)
    if (!credentials) {
      // Web flow - works for both local and remote connections
      // The OAuth redirect URI uses the actual server address, so the callback
      // reaches the relay server which broadcasts results via WebSocket
      const tokenInfo = await getWebGoogleToken();

      if (!tokenInfo) {
        return {
          success: false,
          error: { code: 'invalid_token', message: 'Failed to get Google token' },
        };
      }

      credentials = {
        method: 'google',
        idToken: tokenInfo.idToken,
        accessToken: tokenInfo.accessToken,
      };
      logger.debug('[GoogleOAuth] Got credentials from web OAuth flow');
    }

    // Call backend to validate and create session
    const response = await loginWithGoogle(credentials, {
      useRelay: options?.useRelay ?? config?.useRelay,
      createIfNotExists: options?.createIfNotExists,
    });

    // FALLBACK: If backend validation failed AND we used chrome.identity,
    // retry with web OAuth (handles Vivaldi/non-Chrome browsers where chrome.identity
    // returns a token but it doesn't work properly).
    // Don't retry if needsSignup - that's not an auth failure, user just doesn't exist.
    if (!response.success && !response.needsSignup && usedChromeIdentity) {
      logger.warn('[GoogleOAuth] Backend validation failed with chrome.identity token:', response.error);
      logger.warn('[GoogleOAuth] Retrying with web OAuth flow...');

      try {
        const tokenInfo = await getWebGoogleToken();

        if (!tokenInfo) {
          // Web OAuth also failed - return original error
          return response;
        }

        credentials = {
          method: 'google',
          idToken: tokenInfo.idToken,
          accessToken: tokenInfo.accessToken,
        };

        logger.debug('[GoogleOAuth] Retrying backend validation with web OAuth credentials');
        const retryResponse = await loginWithGoogle(credentials, {
          useRelay: options?.useRelay ?? config?.useRelay,
          createIfNotExists: options?.createIfNotExists,
        });

        return retryResponse;
      } catch (webOAuthError) {
        logger.error('[GoogleOAuth] Web OAuth fallback also failed:', webOAuthError);
        // Return original error from chrome.identity attempt
        return response;
      }
    }

    return response;
  } catch (error) {
    logger.error('[GoogleOAuth] Login failed:', error);
    return {
      success: false,
      error: {
        code: 'invalid_token',
        message: error instanceof Error ? error.message : 'Google login failed',
      },
    };
  }
}

/**
 * Create OAuthConnection from Google token info
 * Used to store Google connection in UserSession
 */
export async function createGoogleConnection(
  accessToken: string,
  options?: {
    refreshToken?: string;
    scopes?: string[];
    isPrimary?: boolean;
    label?: string;
  }
): Promise<OAuthConnection | null> {
  try {
    const userInfo = await fetchGoogleUserInfo(accessToken);

    return createOAuthConnection(
      'google',
      userInfo.sub,
      userInfo.email,
      accessToken,
      options?.scopes ?? DEFAULT_LOGIN_SCOPES,
      {
        name: userInfo.name,
        avatarUrl: userInfo.picture,
        refreshToken: options?.refreshToken,
        expiresAt: Date.now() + 60 * 60 * 1000, // 1 hour default
        isPrimary: options?.isPrimary,
        label: options?.label,
      }
    );
  } catch (error) {
    logger.error('[GoogleOAuth] Failed to create connection:', error);
    return null;
  }
}

// =============================================================================
// LOGOUT
// =============================================================================

/**
 * Revoke Google OAuth access (extension context)
 */
export async function revokeGoogleAccess(): Promise<void> {
  const context = detectOAuthContext();

  if (context === 'extension' && chrome?.identity?.removeCachedAuthToken) {
    // Get current token
    return new Promise<void>((resolve) => {
      chrome.identity.getAuthToken({ interactive: false }, (token) => {
        if (token) {
          chrome.identity.removeCachedAuthToken({ token }, () => {
            resolve();
          });
        } else {
          resolve();
        }
      });
    });
  }

  // For web, the session is managed by SessionManager
  // Google tokens are not cached locally in web context
}
